---
- hosts: cluster
  become: true
  pre_tasks:
    - name: "Add OS variables"
      include_vars: "../family_vars/{{ ansible_os_family | lower }}.yml"
    - name: "Add group variables"
      include_vars: "../group_vars/docker_cache.yml"
  roles:
    - common
    - cri
    - kubernetes
