---
- hosts: masters
  become: true
  pre_tasks:
    - name: "Add OS variables"
      include_vars: "../family_vars/{{ ansible_os_family | lower }}.yml"
  roles:
    - keepalived
    - haproxy
    - cloudflared
