---
- name: Install Helm v3
  shell: |
    curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

- name: Add Cilium Repo
  command:
    cmd: helm repo add cilium https://helm.cilium.io/

- name: Deploy Cilium
  shell: |
    helm upgrade -i cilium cilium/cilium --version {{ cilium_helm_version }} \
    --set global.registry="docker.io/cilium" \
    --set global.tag="{{ cilium_image_version }}" \
    --set global.tunnel="disabled" \
    --set global.externalIPs.enabled="true" \
    --set global.ipam.operator.clusterPoolIPv4PodCIDR="{{ cluster_pod_subnet }}" \
    --set global.ipam.operator.clusterPoolIPv4MaskSize="24" \
    --set global.endpointRoutes.enabled="true" \
    --set global.hostServices.enabled="true" \
    --set global.autoDirectNodeRoutes="true" \
    --set global.nodePort.enabled="true" \
    --set global.nodePort.mode="dsr" \
    --set global.masquerade="false" \
    --set global.hubble.enabled="true" \
    --set global.hubble.ui.enabled="true" \
    --set global.hubble.relay.enabled="true" \
    --set global.hubble.metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,http}" \
    --set global.kubeProxyReplacement=strict \
    --set global.k8sServiceHost={{ k8s_service_host }} \
    --set global.k8sServicePort={{ k8s_service_port }} \
    --set config.bpfMasquerade="false" \
    --namespace kube-system

- name: Create Manifests Directory
  file:
    path: /root/manifests
    state: directory

- name: "Deploy manifests"
  become: true
  template:
    src: "{{ item }}"
    dest: "/root/manifests/{{ item | basename | replace('.j2','') }}"
    mode: 0600
  with_items:
  - "generic-kuberouter-only-advertise-routes.yaml.j2"

- name: Applying manifests
  command:
    cmd: "kubectl apply -f /root/manifests/{{ item }}"
  with_items:
  - "generic-kuberouter-only-advertise-routes.yaml"

- name: Remove Manifests Directory
  file:
    path: /root/manifests
    state: absent
