---
- name: Install Helm v3
  shell: |
    curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
  args:
    warn: false

- name: Add Cilium Repo
  command:
    cmd: helm repo add cilium https://helm.cilium.io/

- name: Update Helm Repos
  command:
    cmd: helm repo update

- name: Deploy Cilium
  shell: |
    helm upgrade -i cilium cilium/cilium --version {{ cilium_helm_version }} \
    --set image.registry="docker.io/cilium" \
    --set image.tag="{{ cilium_image_version }}" \
    --set tunnel="disabled" \
    --set externalIPs.enabled="true" \
    --set ipam.operator.clusterPoolIPv4PodCIDR="{{ cluster_pod_subnet }}" \
    --set ipam.operator.clusterPoolIPv4MaskSize="24" \
    --set nativeRoutingCIDR="10.43.0.0/16" \
    --set endpointRoutes.enabled="true" \
    --set hostServices.enabled="true" \
    --set autoDirectNodeRoutes="true" \
    --set nodePort.enabled="true" \
    --set loadBalancer.mode="dsr" \
    --set loadBalancer.algorithm="maglev" \
    --set maglev.tableSize=16381 \
    --set maglev.hashSeed="4QTbVKvWlrq8h/gU" \
    --set masquerade="true" \
    --set hubble.enabled="true" \
    --set hubble.listenAddress=":4244" \
    --set hubble.ui.enabled="true" \
    --set hubble.relay.enabled="true" \
    --set hubble.metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,http}" \
    --set kubeProxyReplacement=strict \
    --set k8sServiceHost={{ k8s_service_host }} \
    --set k8sServicePort={{ k8s_service_port }} \
    --set bpf.masquerade="true" \
    --namespace kube-system

- name: Create Manifests Directory
  file:
    path: /root/manifests
    state: directory
    mode: 0700

- name: "Deploy manifests"
  become: true
  template:
    src: "{{ item }}"
    dest: "/root/manifests/{{ item | basename | replace('.j2','') }}"
    mode: 0600
  with_items:
  - "generic-kuberouter-only-advertise-routes.yaml.j2"

- name: Applying manifests
  command:
    cmd: "kubectl apply -f /root/manifests/{{ item }}"
  with_items:
  - "generic-kuberouter-only-advertise-routes.yaml"

- name: Remove Manifests Directory
  file:
    path: /root/manifests
    state: absent
