---
- name: 'validate variable : cni_plugin'
  assert:
    that:
      - cni_plugin | type_debug == 'AnsibleUnicode'
    fail_msg:
      - "Variable 'cni_plugin' should be of type AnsibleUnicode (string)"
      - 'Type is: {{ cni_plugin | type_debug }}'
      - "Value is: {{ cni_plugin | default('undefined') }}"

- name: 'validate variable : cni_main_master'
  assert:
    that:
      - (cni_main_master | type_debug == 'AnsibleUnicode') or (cni_main_master | type_debug == 'str')
    fail_msg:
      - "Variable 'cni_main_master' should be of type AnsibleUnicode (string) or str"
      - 'Type is: {{ cni_main_master | type_debug }}'
      - "Value is: {{ cni_main_master | default('undefined') }}"

- name: 'validate plugin support'
  assert:
    that:
      - cni_plugin in cni_supported_plugins
    fail_msg:
      - "Plugin '{{ cni_plugin }}' is not supported at this time."

- name: 'validate pod subnet is used when using flannel'
  assert:
    that:
      - cluster_pod_subnet | ipaddr
    fail_msg:
      - "Plugin 'flannel' requires pod subnet to be configured."
  when: cni_plugin == 'flannel'
