---
- name: ensure kubernetes manifests directory
  file:
    path: /etc/kubernetes/manifests
    state: directory

- name: ensure systemd kubelet directory
  file:
    path: /etc/systemd/system/kubelet.service.d
    state: directory
    mode: 0755

- name: systemd kubelet drop-in
  copy:
    dest: /etc/systemd/system/kubelet.service.d/override.conf
    mode: 0755
    src: override.conf
  notify:
    - restart kubelet

- name: systemd kubelet after docker drop-in
  copy:
    dest: /etc/systemd/system/kubelet.service.d/12-after-docker.conf
    mode: 0755
    src: 12-after-docker.conf
  notify:
    - restart kubelet

- name: kubelet defaults file
  template:
    src: kubelet.default.j2
    dest: /etc/default/kubelet
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart kubelet

- name: ensure kubelet is running and enabled
  service:
    name: kubelet
    state: started
    enabled: yes
