---
- name: include debian family specific tasks
  include_tasks: debian.yml
  when: ansible_os_family | lower == 'debian'

- name: include archlinux family specific tasks
  include_tasks: archlinux.yml
  when: ansible_os_family | lower == 'archlinux'

- name: include common tasks
  include_tasks: common.yml
