---
- name: configure firewall zone assignments
  vyos.vyos.vyos_config:
    lines:
      # DEFINE INTERFACES
      - set zone-policy zone CAMERAS default-action drop
      - set zone-policy zone CAMERAS interface bond0.3000
      - set zone-policy zone LAN default-action drop
      - set zone-policy zone LAN interface bond0
      - set zone-policy zone WAN default-action drop
      - set zone-policy zone WAN interface bond0.4000
      - set zone-policy zone WIRELESS default-action drop
      - set zone-policy zone WIRELESS interface bond0.30
      - set zone-policy zone SERVERS default-action drop
      - set zone-policy zone SERVERS interface bond0.20

      # ATTACH POLICIES TO INTERFACES
      - set zone-policy zone WAN from CAMERAS firewall name CAMERAS-WAN
      - set zone-policy zone WAN from LAN firewall name LAN-WAN
      - set zone-policy zone WAN from WIRELESS firewall name WIRELESS-WAN
      - set zone-policy zone WAN from SERVERS firewall name SERVERS-WAN

      - set zone-policy zone CAMERAS from WAN firewall name WAN-CAMERAS
      - set zone-policy zone CAMERAS from LAN firewall name LAN-CAMERAS

      - set zone-policy zone LAN from WAN firewall name WAN-LAN
      - set zone-policy zone LAN from SERVERS firewall name SERVERS-LAN
      - set zone-policy zone LAN from CAMERAS firewall name CAMERAS-LAN

      - set zone-policy zone WIRELESS from WAN firewall name WAN-WIRELESS
      - set zone-policy zone WIRELESS from SERVERS firewall name SERVERS-WIRELESS

      - set zone-policy zone SERVERS from WAN firewall name WAN-SERVERS
      - set zone-policy zone SERVERS from LAN firewall name LAN-SERVERS
      - set zone-policy zone SERVERS from WIRELESS firewall name WIRELESS-SERVERS
