---
cni_plugin: calico
cni_bgp_peer_address: 10.20.0.1
cni_bgp_peer_asn: 64512
cni_cilium_image_repository: docker.io/cilium/cilium-dev
cni_cilium_helm_version: 1.9.3
cni_cilium_image_version: v1.9.3
cni_cilium_hubble_enabled: false
cni_cilium_enovy_proxy_image_version: v1.16.2
cni_cilium_bpf_hostrouting: "true"
cni_cilium_bpf_tproxy: "false"
cni_cilium_bpf_masquerade: "true"
cni_cilium_endpoint_routes: "false"
k8s_service_host: '{{ cluster_control_plane_endpoint | regex_search("[a-z0-9\-._~%]+") }}'
k8s_service_port: '{{ cluster_control_plane_endpoint | regex_search("(?<=:)(?P<port>[0-9]+)$") }}'
kube_router_image: docker.io/cloudnativelabs/kube-router
cluster_pod_subnet: 10.0.0.0/8
k8s_native_cluster_cidr: "{{ (ansible_default_ipv4.network + '/' + ansible_default_ipv4.netmask) | ipaddr('network/prefix') }}"
cni_kube_router_enabled: false
