---
- name: check os_family support
  assert:
    that:
      - ansible_os_family | lower in nfs_supported_os_families
    fail_msg:
      - "os_family '{{ ansible_os_family }}' is not supported at this time"

- name: 'validate variable : nfs_enabled'
  assert:
    that:
      - nfs_enabled | type_debug == 'bool'
    fail_msg:
      - "Variable 'nfs_enabled' should be of type 'bool'"
      - 'Type is: {{ nfs_enabled | type_debug }}'
      - "Value is: {{ nfs_enabled | default('undefined') }}"
