---
- name: read config json
  ansible.builtin.include_role:
    name: get_config_json

- name: dhcp-server
  vars:
    current_config: "{{ vyos_active_config['service']['dhcp-server'] | default({}) }}"
  vyos.vyos.vyos_config:
    match: line
    lines: "{{ lookup('template', './config/dhcp-server.j2') }}"
