---
- name: read config json
  ansible.builtin.include_role:
    name: get_config_json

- name: igmp-proxy
  vars:
    current_config: "{{ vyos_active_config['protocol']['igmp-proxy'] | default({}) }}"
  vyos.vyos.vyos_config:
    match: line
    lines: "{{ lookup('template', './config/igmp-proxy.j2') }}"
  tags:
    - igmp-proxy
