vault_DOMAIN: "mydomain.local"
vault_VAULT_RECOVERY_TOKEN: [u'GK9esTphailnb1rfO7dIr1IKgkzlrO4hVZaReV5tmRa0', u'SpS+/jjrMnzWW6zor2Xki/q+jNqZXWEiXXWtMcfjkkkP', u'LlL37tQKgLXTOjN1R04kWmw4TMb9uW0S6/Lwffssiorx', u'hV4IYHHIH2Qh/feMYEMt1dJgRlQearike+ai3lgJsQ4B', u'xvnc3pHbGxCd9z4Osb3myyIon/aA4DYcSVBteILIm+8H']
vault_VAULT_ROOT_TOKEN: s.TaeMEjXANqHtyBqUvBJnwOC4
