---
# - name: Define bond0
#   vyos.vyos.vyos_lag_interfaces:
#     config:
#     - name: bond0
#       mode: 802.3ad
#       members:
#       - member: eth0
#       - member: eth1
#       - member: eth2
#       - member: eth3
#     state: overridden

- name: configure bond
  vyos.vyos.vyos_config:
    lines:
      - set interfaces bonding bond0 member interface eth0
      - set interfaces bonding bond0 member interface eth1
      - set interfaces bonding bond0 member interface eth2
      - set interfaces bonding bond0 member interface eth3

- name: Create VIFs
  vyos.vyos.vyos_interfaces:
    config:
    - name: bond0
      description: LAN
      vifs:
      - vlan_id: 20
        description: SERVERS
      - vlan_id: 30
        description: WIRELESS
      - vlan_id: 4000
        description: WAN
    state: overridden

- name: configure interface addresses
  vyos.vyos.vyos_config:
    lines:
      - set interfaces bonding bond0 vif 4000 address 'dhcp'
      - set interfaces bonding bond0 vif 4000 address 'dhcpv6'
      - set interfaces bonding bond0 address '{{ LAN.GW }}/24'
      - set interfaces bonding bond0 vif 20 address '{{ SERVERS.GW }}/16'
      - set interfaces bonding bond0 vif 30 address '{{ WIRELESS.GW }}/16'

- name: configure interface NAT
  vyos.vyos.vyos_config:
    lines:
      - set nat source rule 999999 outbound-interface 'bond0.4000'
      # - set nat source rule 999999 source address '{{ LAN.CIDR }}'
      - set nat source rule 999999 translation address 'masquerade'
      # - set nat source rule 10 outbound-interface 'eth0'
      # - set nat source rule 10 source address '{{ VLAN_10.CIDR }}'
      # - set nat source rule 10 translation address 'masquerade'
      # - set nat source rule 99 outbound-interface 'eth0'
      # - set nat source rule 99 source address '{{ VLAN_99.CIDR }}'
      # - set nat source rule 99 translation address 'masquerade'
      # - set nat source rule 100 outbound-interface 'eth0'
      # - set nat source rule 100 source address '{{ VLAN_100.CIDR }}'
      # - set nat source rule 100 translation address 'masquerade'
      # - set nat source rule 101 outbound-interface 'eth0'
      # - set nat source rule 101 source address '{{ VLAN_101.CIDR }}'
      # - set nat source rule 101 translation address 'masquerade'

