---

- name: configure Forced DNS port forward (LAN) -- Exclude DNS Server
  vyos.vyos.vyos_config:
    lines:
      - set nat destination rule 10 description 'DNS Forced Redirect (LAN) -- Exclude DNS Server'
      - set nat destination rule 10 destination port '53'
      - set nat destination rule 10 destination address !10.45.10.13
      - set nat destination rule 10 inbound-interface bond0
      - set nat destination rule 10 protocol 'tcp_udp'
      - set nat destination rule 10 translation address '10.45.10.13'

- name: configure Forced DNS port forward (LAN) -- Exclude Upstream
  vyos.vyos.vyos_config:
    lines:
      - set nat destination rule 11 description 'DNS Forced Redirect (LAN) -- Exclude Upstream'
      - set nat destination rule 11 destination port '53'
      - set nat destination rule 11 destination address !10.20.0.1
      - set nat destination rule 11 inbound-interface bond0
      - set nat destination rule 11 protocol 'tcp_udp'
      - set nat destination rule 11 translation address '10.45.10.13'

- name: configure Forced DNS port forward (WIRELESS) -- Exclude DNS Server
  vyos.vyos.vyos_config:
    lines:
      - set nat destination rule 12 description 'DNS Forced Redirect (WIRELESS) -- Exclude DNS Server'
      - set nat destination rule 12 destination port '53'
      - set nat destination rule 12 destination address !10.45.10.13
      - set nat destination rule 12 inbound-interface bond0.30
      - set nat destination rule 12 protocol 'tcp_udp'
      - set nat destination rule 12 translation address '10.45.10.13'

- name: configure Forced DNS port forward (WIRELESS) -- Exclude Upstream
  vyos.vyos.vyos_config:
    lines:
      - set nat destination rule 13 description 'DNS Forced Redirect (WIRELESS) -- Exclude Upstream'
      - set nat destination rule 13 destination port '53'
      - set nat destination rule 13 destination address !10.20.0.1
      - set nat destination rule 13 inbound-interface bond0.30
      - set nat destination rule 13 protocol 'tcp_udp'
      - set nat destination rule 13 translation address '10.45.10.13'

- name: configure PLEX port forward
  vyos.vyos.vyos_config:
    lines:
      - set nat destination rule 1000 description 'Plex PortForward'
      - set nat destination rule 1000 destination port '{{ PLEX.PORT }}'
      - set nat destination rule 1000 inbound-interface 'bond0.4000'
      - set nat destination rule 1000 protocol 'tcp'
      - set nat destination rule 1000 translation address '{{ PLEX.ADDRESS }}'

- name: configure INGRESS HTTP port forward
  vyos.vyos.vyos_config:
    lines:
      - set nat destination rule 8080 description 'INGRESS PortForward HTTP'
      - set nat destination rule 8080 destination port '80'
      - set nat destination rule 8080 inbound-interface 'bond0.4000'
      - set nat destination rule 8080 protocol 'tcp'
      - set nat destination rule 8080 translation address '{{ KUBERNETES.INGRESS }}'

- name: configure INGRESS HTTPS port forward
  vyos.vyos.vyos_config:
    lines:
      - set nat destination rule 8443 description 'INGRESS PortForward HTTPS'
      - set nat destination rule 8443 destination port '443'
      - set nat destination rule 8443 inbound-interface 'bond0.4000'
      - set nat destination rule 8443 protocol 'tcp'
      - set nat destination rule 8443 translation address '{{ KUBERNETES.INGRESS }}'
