---
- name: configure mDNS repeater
  vyos.vyos.vyos_config:
    lines:
      - set service mdns repeater interface 'bond0'
      - set service mdns repeater interface 'bond0.20'
      - set service mdns repeater interface 'bond0.30'
