---
- name: Add user to sudoers
  copy:
    content: "{{ ansible_user }} ALL=(ALL:ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/{{ ansible_user }}_nopasswd"
    mode: 0440

- name: Remove motd
  command: update-rc.d motd remove

- name: Quite the login prompt
  file:
    dest: "/home/{{ ansible_user }}/.hushlogin"
    state: touch
    owner: "{{ ansible_user }}"
    mode: 0775

- name: Create config directory
  file:
    path: "/home/{{ ansible_user }}/.config"
    state: directory
    recurse: true
    owner: "{{ ansible_user }}"
    mode: 0775

- name: Create neofetch directory
  file:
    path: "/home/{{ ansible_user }}/.config/neofetch"
    state: directory
    recurse: true
    owner: "{{ ansible_user }}"
    mode: 0775

- name: Add custom neofetch config
  copy:
    src: neofetch.conf
    dest: "/home/{{ ansible_user }}/.config/neofetch/config.conf"
    owner: "{{ ansible_user }}"
    mode: 0775

- name: Enable neofetch on login for Ubuntu
  copy:
    content: "neofetch"
    dest: "/home/{{ ansible_user }}/.bash_profile"
    owner: "{{ ansible_user }}"
    mode: 0775
