---
- name: 'initialize | create configuration file for kubeadm'
  ansible.builtin.template:
    src: 'kubeadm-config.yaml.j2'
    dest: '/etc/kubernetes/kubeadm-config.yaml'
    mode: 0640

- name: 'initialize | execute kubeadm init on first control plane node'
  ansible.builtin.command: >
    kubeadm init --config /etc/kubernetes/kubeadm-config.yaml
    {% if not cluster_kube_proxy_enabled %}
    --skip-phases='addon/kube-proxy'
    {% endif %}
    --upload-certs
  register: kubeadm_init

- name: 'initialize | set cluster_initialized fact'
  ansible.builtin.set_fact:
    cluster_initialized: true
  run_once: true
  when: kubeadm_init.rc == 0

- name: 'initialize | create kubectl config directory'
  ansible.builtin.file:
    path: '/root/.kube/'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: 0750

- name: 'initialize | copy admin.conf to kubectl config directory'
  ansible.builtin.copy:
    src: '/etc/kubernetes/admin.conf'
    dest: '/root/.kube/config'
    owner: 'root'
    group: 'root'
    mode: 0750
    remote_src: true
    backup: true

- name: 'initialize | copy Kubernetes config locally'
  ansible.builtin.fetch:
    src: '/etc/kubernetes/admin.conf'
    dest: 'output/k8s-config.yaml'
    flat: true
