---
- name: copy coredns corefile
  ansible.builtin.template:
    src: coredns/Corefile.j2
    dest: "{{ coredns['config_path'] }}/Corefile"
    owner: root
    group: vyattacfg
    mode: "0775"
    lstrip_blocks: true
  become: true
  notify:
    - restart coredns service unit

- name: copy coredns service unit
  ansible.builtin.template:
    src: coredns/coredns.service.j2
    dest: /etc/systemd/system/coredns.service
    owner: root
    group: vyattacfg
    mode: "0775"
    lstrip_blocks: true
  become: true
  notify:
    - reload systemd daemon
    - restart coredns service unit

- name: start coredns unit
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: coredns
  become: true
