---
- name: create kubeconfig
  run_once: true
  vars:
    service_account_raw: "{{ lookup('kubernetes.core.k8s', namespace=coredns['k8s_gateway']['service_account_ns'], kind='ServiceAccount', resource_name=coredns['k8s_gateway']['service_account']) }}"
    service_account_token: "{{ service_account_raw | json_query('secrets[*].name | [0]') }}"
    certificate_authority_raw: "{{ lookup('kubernetes.core.k8s', namespace=coredns['k8s_gateway']['service_account_ns'], kind='Secret', resource_name=service_account_token) }}"
    certificate_authority: '{{ certificate_authority_raw | json_query(''data."ca.crt"'') }}'
    certificate_authority_token: "{{ certificate_authority_raw | json_query('data.token') | b64decode }}"
  ansible.builtin.template:
    src: coredns/kubeconfig.j2
    dest: "{{ coredns['config_path'] }}/kubeconfig"
    owner: root
    group: vyattacfg
    mode: "0775"
    lstrip_blocks: true
  become: true
  notify:
    - restart coredns service unit
