---
- name: set facts for ansible ssh
  when:
    - coredns['enabled']
  set_fact:
    ansible_connection: ssh

- name: create CoreDNS config directory on host
  when:
    - coredns['enabled']
  ansible.builtin.file:
    path: "{{ coredns['config_path'] }}"
    state: directory
    owner: root
    group: vyattacfg
    mode: "0755"
  become: true

- name: create kubeconfig
  when:
    - coredns['enabled']
    - coredns['k8s_gateway']['enabled']
  run_once: true
  vars:
    service_account_raw: "{{ lookup('kubernetes.core.k8s', namespace=coredns['k8s_gateway']['service_account_ns'], kind='ServiceAccount', resource_name=coredns['k8s_gateway']['service_account']) }}"
    service_account_token: "{{ service_account_raw | json_query('secrets[*].name | [0]') }}"
    certificate_authority_raw: "{{ lookup('kubernetes.core.k8s', namespace=coredns['k8s_gateway']['service_account_ns'], kind='Secret', resource_name=service_account_token) }}"
    certificate_authority: '{{ certificate_authority_raw | json_query(''data."ca.crt"'') }}'
    certificate_authority_token: "{{ certificate_authority_raw | json_query('data.token') | b64decode }}"
  ansible.builtin.template:
    src: coredns/kubeconfig.j2
    dest: "{{ coredns['config_path'] }}/kubeconfig"
    owner: root
    group: vyattacfg
    mode: "0775"
    lstrip_blocks: true
  become: true

- name: copy coredns corefile
  when:
    - coredns['enabled']
  ansible.builtin.template:
    src: coredns/Corefile.j2
    dest: "{{ coredns['config_path'] }}/Corefile"
    owner: root
    group: vyattacfg
    mode: "0775"
    lstrip_blocks: true
  become: true

- name: copy coredns service unit
  ansible.builtin.template:
    src: coredns/coredns.service.j2
    dest: /etc/systemd/system/coredns.service
    owner: root
    group: vyattacfg
    mode: "0775"
    lstrip_blocks: true
  become: true
  notify:
    - reload systemd daemon
    - restart coredns service unit

- name: start coredns unit
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: coredns
  become: true
