---
REPO_ROOT: "{{ lookup('pipe', 'git rev-parse --show-toplevel') }}"
common_timezone: America/New_York
cri_plugin: containerd
cni_plugin: calico
common_log2ram_enabled: false
cluster_extra_sans:
  - k8s.holthome.net
  - 10.43.0.1
  - kubernetes
cluster_control_plane_endpoint: "k8s.holthome.net:6443"
cluster_pod_subnet: "10.42.0.0/16"
cluster_external_subnet: "10.43.0.0/16"
cilium_helm_version: 1.9.1
cilium_image_version: v1.9
github_username: carpenike
github_k8s_reponame: k8s-gitops
github_k8s_reponame_branch: master
bgp_peer_address: 10.20.0.1
bgp_peer_asn: 64512
bgp_cluster_asn: 64513
kube_router_image: "docker.io/cloudnativelabs/kube-router:v1.1.1"
kubernetes_kubelet_version: 1.20.4-00
kubernetes_kubeadm_version: 1.20.4-00
kubernetes_kubectl_version: 1.20.4-00
etcd_ca_file: /etc/kubernetes/pki/etcd/ca.crt
etcd_cert_file: /etc/kubernetes/pki/etcd/server.crt
etcd_cert_key_file: /etc/kubernetes/pki/etcd/server.key
kube_proxy: enabled
