---
- name: Converge
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Install git
      apt:
        name: git
        update_cache: true
    - name: "Include common"
      include_role:
        name: "common"
  vars:
    common_reboot_handler_enabled: false
