---

cluster_name: kubernetes
cluster_extra_sans:
- k8s.holthome.net
- 10.43.0.1
- kubernetes
cluster_control_plane_endpoint: 'k8s.holthome.net:6443'

# Specify the Kubernetes version, current release is v1.20.0
cluster_kubernetes_version: 'v1.20.2'

cluster_apiserver_enable_admission_plugins:
- 'NodeRestriction'

cluster_cgroup_driver: 'systemd'

# Profiling; Enable profiling via web interface host:port/debug/pprof/
cluster_profiling: false

# The below parameters set the internal network for Kubernetes, this configuration
# provides a maximum of 64 nodes in a cluster and 254 pods per node.

# Kubernetes internal network for services, *must* be an unused block of space.
cluster_service_subnet: '10.43.0.0/16'

# Kubernetes internal network. IP's for pods will be drawn from this address
# space. *must* be unused in your network infrastructure.
cluster_pod_subnet: '10.42.0.0/16'

# This sets the network node allocation size. Each node in the cluster is
# assigned a subnet of this size.
cluster_node_network_prefix: 24

# Cluster Authorization Modes for the Kubernetes Cluster
# Available Options: 'AlwaysAllow','AlwaysDeny','Node' and 'RBAC'
# Order is relevant
cluster_authorization_modes: ['Node', 'RBAC']

# Vars for discoverying kubernetes api endpoints
# will refactor to eliminate this variable
cluster_primary_control_node: '{{ groups["masters"]|first }}'
cluster_apiserver_count: '{{ groups["masters"]|length }}'

# Tuning for arm64 platforms; https://etcd.io/docs/v3.4.0/tuning/
cluster_etcd_heartbeat_interval: 250
cluster_etcd_election_timeout: 1250
cluster_etcd_snapshot_count: 5000

# Kube Proxy mode either ipvs or iptables; Default iptables
cluster_kube_proxy_mode: 'ipvs'
