---
- name: add bgp policies
  vyos.vyos.vyos_config:
    lines:
      - set policy prefix-list HOME-NETS rule 1 action permit
      - set policy prefix-list HOME-NETS rule 1 prefix 10.9.18.0/24
      - set policy prefix-list HOME-NETS rule 2 action permit
      - set policy prefix-list HOME-NETS rule 2 prefix 10.20.0.0/16
      - set policy prefix-list HOME-NETS rule 3 action permit
      - set policy prefix-list HOME-NETS rule 3 prefix 10.42.0.0/16
      - set policy prefix-list HOME-NETS rule 4 action permit
      - set policy prefix-list HOME-NETS rule 4 prefix 10.43.0.0/16
      - set policy prefix-list HOME-NETS rule 5 action permit
      - set policy prefix-list HOME-NETS rule 5 prefix 10.45.0.0/16
      - set policy route-map TO-RACKNERD rule 1 action permit
      - set policy route-map TO-RACKNERD rule 1 match ip address prefix-list HOME-NETS

- name: configure bgp
  vyos.vyos.vyos_config:
    lines:
      - set protocols bgp local-as 64512
      - set protocols bgp address-family ipv4-unicast redistribute connected
      - set protocols bgp neighbor 10.20.10.16 remote-as 64512
      - set protocols bgp neighbor 10.20.10.20 remote-as 64512
      - set protocols bgp neighbor 10.20.10.21 remote-as 64512
      - set protocols bgp neighbor 10.20.10.22 remote-as 64512
      - set protocols bgp neighbor 10.20.10.23 remote-as 64512
      - set protocols bgp neighbor 192.168.10.2 remote-as 64513
      - set protocols bgp neighbor 192.168.10.2 address-family ipv4-unicast prefix-list export HOME-NETS
