---
- name: check os_family support
  assert:
    that:
      - ansible_os_family | lower in zfs_supported_os_families
    fail_msg:
      - "os_family '{{ ansible_os_family }}' is not supported at this time"

- name: 'validate variable : zfs_enabled'
  assert:
    that:
      - zfs_enabled | type_debug == 'bool'
    fail_msg:
      - "Variable 'zfs_enabled' should be of type 'bool'"
      - 'Type is: {{ zfs_enabled | type_debug }}'
      - "Value is: {{ zfs_enabled | default('undefined') }}"
