---
- name: pacman upgrade
  pacman:
    upgrade: true
    update_cache: true
  register: pacman_upgrade
  retries: 5
  until: pacman_upgrade is success
  when: common_upgrade_packages

- name: install packages
  pacman:
    name: '{{ common_packages }}'
    update_cache: true
  register: pacman_install_common
  retries: 5
  until: pacman_install_common is success

- name: install common Kubernetes ansible module
  pip:
    name:
      - openshift

- name: enable required cgroup features
  lineinfile:
    path: '{{ common_rpi_cmd_file }}'
    state: present
    backrefs: true
    regexp: '^(.*elevator=noop(?<!cgroup_enable=memory cgroup_memory=1))$'
    line: '\1 cgroup_enable=memory cgroup_memory=1'
  notify: reboot hosts

- name: disable uas driver on usb ssd
  lineinfile:
    path: '{{ common_rpi_cmd_file }}'
    state: present
    backrefs: true
    regexp: '^(.*rw rootwait(?<!usb-storage.quirks={{ common_usb_ssd_device_id }}:u)) (console=.*)$'
    line: '\1 usb-storage.quirks={{ common_usb_ssd_device_id }}:u \2'
  when: common_usb_ssd_enabled
  notify: reboot hosts

- name: check for yay
  stat:
    path: /usr/bin/yay
  register: yay

- name: create temp folder
  tempfile:
    state: directory
    suffix: yay
  register: tempfolder
  become: false
  when:
    - not yay.stat.exists

- name: checkout yay repo
  git:
    repo: https://aur.archlinux.org/yay.git
    version: master
    dest: "{{ tempfolder.path }}"
    depth: 1
  become: false
  when:
    - not yay.stat.exists

- name: build and install yay
  command:
    chdir: "{{ tempfolder.path }}"
    cmd: makepkg -si --noconfirm
  become: false
  when:
    - not yay.stat.exists

- name: remove temp folder
  file:
    path: "{{ tempfolder.path }}"
    state: absent
  when:
    - not yay.stat.exists
