---
- name: apt-get upgrade
  apt:
    upgrade: full
    update_cache: true
    cache_valid_time: 3600
    force_apt_get: true
    autoclean: true
    autoremove: true
  register: apt_upgrade
  retries: 5
  until: apt_upgrade is success
  when: common_upgrade_packages

- name: install common packages
  apt:
    name: '{{ common_packages }}'
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600
    force_apt_get: true
    autoclean: true
    autoremove: true
  register: apt_install_common
  retries: 5
  until: apt_install_common is success

- name: install common Kubernetes ansible module
  pip:
    name:
      - openshift

- name: install and configure log2ram
  include_tasks: log2ram.yml
  when: common_log2ram_enabled
