---
- name: define servers-cameras rules
  vyos.vyos.vyos_firewall_rules:
    config:
      - afi: ipv4
        rule_sets:
          - name: SERVERS-CAMERAS
            description: SERVERS to CAMERAS Rule Set
            default_action: accept
            enable_default_log: yes
    state: merged
