---
- name: define wan-servers rules
  vyos.vyos.vyos_firewall_rules:
    config:
      - afi: ipv4
        rule_sets:
          - name: WAN-SERVERS
            description: WAN to SERVERS Rule Set
            default_action: drop
            enable_default_log: yes
            rules:
              - number: 1
                action: accept
                description: Allow Established and Related to SERVERS
                state:
                  established: true
                  new: false
                  invalid: false
                  related: true
              - number: 2
                action: drop
                description: Drop Invalid to SERVERS
                state:
                  established: false
                  new: false
                  invalid: true
                  related: false
              - number: 100
                action: accept
                description: HTTP to Ingress
                state:
                  established: false
                  new: true
                  invalid: false
                  related: false
                destination:
                  port: http
                  address: "{{ KUBERNETES.INGRESS }}"
                protocol: tcp
              - number: 101
                action: accept
                description: HTTPS to Ingress
                state:
                  established: false
                  new: true
                  invalid: false
                  related: false
                destination:
                  port: https
                  address: "{{ KUBERNETES.INGRESS }}"
                protocol: tcp
              - number: 200
                action: accept
                description: 32400 to Plex
                state:
                  established: false
                  new: true
                  invalid: false
                  related: false
                destination:
                  port: "{{ PLEX.PORT }}"
                  address: "{{ PLEX.ADDRESS }}"
                protocol: tcp
    state: merged
