---
- name: define wan-lan rules
  vyos.vyos.vyos_firewall_rules:
    config:
      - afi: ipv4
        rule_sets:
          - name: WAN-LAN
            description: WAN to LAN Rule Set
            default_action: drop
            enable_default_log: yes
            rules:
              - number: 1
                action: accept
                description: Allow Established and Related to LAN
                state:
                  established: true
                  new: false
                  invalid: false
                  related: true
              - number: 2
                action: drop
                description: Drop Invalid to LAN
                state:
                  established: false
                  new: false
                  invalid: true
                  related: false
    state: merged
