---

- name: Create directory .kube
  delegate_to: localhost
  become: no
  file:
    path: ~/.kube
    state: directory
    owner: '{{ local_user }}'
  when: ( k3s_copy_config_local == true )

- name: Copy config file to user setup directory
  run_once: yes
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: '{{ REPO_ROOT }}/kubeconfig'
    owner: '{{ local_user }}'
    flat: yes

- name: Copy config file to user home directory
  run_once: yes
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: '~/.kube/config'
    owner: '{{ local_user }}'
    flat: yes
  when: ( k3s_copy_config_local == true )

- name: Replace https://localhost:6443 by https://{{ k3s_control_node_address }}:6443
  run_once: yes
  become: no
  delegate_to: localhost
  replace:
    path: '{{ REPO_ROOT }}/kubeconfig'
    regexp: 'https://127.0.0.1:6443'
    replace: 'https://{{ k3s_control_node_address }}:6443'

- name: Replace https://localhost:6443 by https://{{ k3s_control_node_address }}:6443 (Home File)
  run_once: yes
  become: no
  delegate_to: localhost
  replace:
    path: '~/.kube/config'
    regexp: 'https://127.0.0.1:6443'
    replace: 'https://{{ k3s_control_node_address }}:6443'
  when: ( k3s_copy_config_local == true )
