---
all:
  hosts:
    h2-0:
      hostname: h2-0.holthome.net
      ansible_host: h2-0.holthome.net
    node-0:
      hostname: node-0.holthome.net
      ansible_host: node-0.holthome.net
    node-1:
      hostname: node-1.holthome.net
      ansible_host: node-1.holthome.net
    node-2:
      hostname: node-2.holthome.net
      ansible_host: node-2.holthome.net
    node-3:
      hostname: node-3.holthome.net
      ansible_host: node-3.holthome.net

controlplane:
  hosts:
    h2-0:
      hostname: h2-0.holthome.net
      ansible_host: h2-0.holthome.net

nodes:
  hosts:
    node-0:
      hostname: node-0.holthome.net
      ansible_host: node-0.holthome.net
    node-1:
      hostname: node-1.holthome.net
      ansible_host: node-1.holthome.net
    node-2:
      hostname: node-2.holthome.net
      ansible_host: node-2.holthome.net
    node-3:
      hostname: node-3.holthome.net
      ansible_host: node-3.holthome.net

workers:
  hosts:
    node-0:
      hostname: node-0.holthome.net
      ansible_host: node-0.holthome.net
    node-1:
      hostname: node-1.holthome.net
      ansible_host: node-1.holthome.net
    node-2:
      hostname: node-2.holthome.net
      ansible_host: node-2.holthome.net
    node-3:
      hostname: node-3.holthome.net
      ansible_host: node-3.holthome.net

masters:
  hosts:
    h2-0:
      hostname: h2-0.holthome.net
      ansible_host: h2-0.holthome.net

cluster:
  children:
    controlplane:
    nodes:

k8s:
  children:
    masters:
    workers:

vault:
  hosts:
    localhost:
      ansible_connection: local
