---
masters:
  hosts:
    h2-0:
      hostname: h2-0.holthome.net
      ansible_host: h2-0.holthome.net
workers:
  hosts:
    r610-0:
      hostname: r610-0.holthome.net
      ansible_host: r610-0.holthome.net
    r610-1:
      hostname: r610-1.holthome.net
      ansible_host: r610-1.holthome.net
    r610-2:
      hostname: r610-2.holthome.net
      ansible_host: r610-2.holthome.net
    r720-0:
      hostname: r720-0.holthome.net
      ansible_host: r720-0.holthome.net
    # n2-0:
    #   ansible_host: n2-0.holthome.net

# arm:
#   hosts:
#     n2-0:
#       ansible_host: n2-0.holthome.net

cluster:
  children:
    masters:
    workers:

storage:
  children:
    ceph:
    nfs:

vault:
  hosts:
    localhost:
      ansible_connection: local
