---
- name: preflight checks
  include_tasks: pre_checks.yml
  run_once: true

- name: cluster checks
  include_tasks: cluster_checks.yml

- name: include initialize tasks
  include_tasks: initialize.yml
  when:
    - inventory_hostname == cluster_main_master
    - not cluster_node_configured

- name: include join tasks
  include_tasks: join.yml
  when: inventory_hostname != cluster_main_master
