---
cluster_name: kubernetes
cluster_extra_sans:
  - "{{ keepalived_vip }}"
cluster_control_plane_endpoint: "" # defaults to '{{ keepalived_vip }}:8443' when left empty
cluster_enable_admission_plugins: "NodeRestriction,AlwaysPullImages"
cluster_authorization_mode: "Node,RBAC"
cluster_audit_log_path: "/var/log/kubernetes/audit.log"
cluster_audit_log_maxage: "30"
cluster_audit_log_maxbackup: "10"
cluster_audit_log_maxsize: "100"
cluster_pod_subnet: ""
# Default etcd values, change these if you experience "leader changed" issues when running on a SD card
cluster_etcd_heartbeat_interval: 100
cluster_etcd_election_timeout: 1000
