---
- name: Remove /var/lib/rook
  ignore_errors: yes
  file:
    state: absent
    path: "/var/lib/rook"

- name: Zap the drives
  become: true
  command: "{{ item }}"
  ignore_errors: yes
  with_items:
    - sgdisk --zap-all /dev/sdb
    - sgdisk --zap-all /dev/sdc
    - sgdisk --zap-all /dev/sdd
  when:
    - storage is defined
    - storage == 'ceph'

- name: Remove LVM partitions
  become: true
  shell: "{{ item }}"
  ignore_errors: yes
  with_items:
    - ls /dev/mapper/ceph--* | xargs -I% -- fuser --kill %
    - ls /dev/mapper/ceph--* | xargs -I% -- dmsetup clear %
    - ls /dev/mapper/ceph--* | xargs -I% -- dmsetup remove -f %
    - ls /dev/mapper/ceph--* | xargs -I% -- rm -rf %
  when:
    - storage is defined
    - storage == 'ceph'

- name: Wipe the block device
  become: true
  command: "{{ item }}"
  ignore_errors: yes
  with_items:
    - wipefs -af /dev/sdb
    - wipefs -af /dev/sdc
    - wipefs -af /dev/sdd
  when:
    - storage is defined
    - storage == 'ceph'

# - name: Rebooting hosts
#   reboot:
#     msg: "Systems are being rebooted"
#     reboot_timeout: 600
#   ignore_errors: true
#   when: ( storage == 'ceph')
