---
address_book:
  hosts:
    ########################
    ### Non-DHCP Clients ###
    ########################
    fw:
      hostname: fw
      network: vlan_servers
      dhcp_client: false
      ipv4_hostid: 1
      groups:
        - fw
    cp-0:
      hostname: cp-0
      network: vlan_servers
      dhcp_client: false
      ipv4_addr: 10.20.0.20
      groups:
        - k8s_nodes
    cp-1:
      hostname: cp-1
      network: vlan_servers
      dhcp_client: false
      ipv4_addr: 10.20.0.21
      groups:
        - k8s_nodes
    cp-2:
      hostname: cp-2
      network: vlan_servers
      ipv4_addr: 10.20.0.22
      groups:
        - k8s_nodes
    nas-0:
      hostname: nas-0
      network: vlan_servers
      aliases:
        - nas.holthome.net
      dhcp_client: false
      ipv4_addr: 10.20.0.10
      groups:
        - nas_nodes
    nas-0-ipmi:
      hostname: nas-0-ipmi
      network: lan
      dhcp_client: false
      ipv4_addr: 10.9.18.10
      groups:
        - ipmi
    nas-1:
      hostname: nas-1
      network: vlan_servers
      dhcp_client: false
      ipv4_addr: 10.20.0.11
      groups:
        - nas_nodes
    nas-1-ipmi:
      hostname: nas-1-ipmi
      network: lan
      dhcp_client: false
      ipv4_addr: 10.9.18.11
      groups:
        - ipmi
    node-0:
      hostname: node-0
      network: vlan_servers
      dhcp_client: false
      ipv4_addr: 10.20.10.20
      groups:
        - k8s_nodes
    node-0-ipmi:
      hostname: node-0-ipmi
      network: lan
      dhcp_client: false
      ipv4_addr: 10.9.18.20
      groups:
        - ipmi
    node-1:
      hostname: node-1
      network: vlan_servers
      dhcp_client: false
      ipv4_addr: 10.20.10.21
      groups:
        - k8s_nodes
    node-1-ipmi:
      hostname: node-1-ipmi
      network: lan
      dhcp_client: false
      ipv4_addr: 10.9.18.21
      groups:
        - ipmi
    node-2:
      hostname: node-2
      network: vlan_servers
      dhcp_client: false
      ipv4_addr: 10.20.10.22
      groups:
        - k8s_nodes
    node-2-ipmi:
      hostname: node-2-ipmi
      network: lan
      dhcp_client: false
      ipv4_addr: 10.9.18.22
      groups:
        - ipmi
    node-3:
      hostname: node-3
      network: vlan_servers
      dhcp_client: false
      ipv4_addr: 10.20.10.23
      groups:
        - k8s_nodes
    node-3-ipmi:
      hostname: node-3-ipmi
      network: lan
      dhcp_client: false
      ipv4_addr: 10.9.18.23
      groups:
        - ipmi
    pki:
      hostname: pki
      network: vlan_servers
      dhcp_client: false
      ipv4_addr: 10.20.0.15
      groups:
        - pki
    sm-0:
      hostname: sm-0
      network: vlan_servers
      dhcp_client: false
      ipv4_addr: 10.20.10.18
      groups:
        - utility

    ####################
    ### DHCP Clients ###
    ####################
    bcs:
      hostname: bcs
      mac_addr: aa:00:02:00:24:0f
      network: lan
      dhcp_client: true
      ipv4_addr: 10.9.18.50
      groups:
        - bcs
    rydesk:
      hostname: rydesk
      mac_addr: 7e:c9:9f:f0:08:15
      network: lan
      dhcp_client: true
      ipv4_addr: 10.9.18.200
      groups:
        - nfs_clients
        - smb_clients
        - plex_clients
    Ryan-PC:
      hostname: Ryan-PC
      mac_addr: 52:54:00:f5:e6:19
      network: lan
      dhcp_client: true
      ipv4_addr: 10.9.18.198
      groups:
        - nfs_clients
        - smb_clients
        - plex_clients
    nintendo-switch-1:
      hostname: nintendo-switch-1
      mac_addr: 58:2f:40:7c:25:19
      network: vlan_wireless
      dhcp_client: true
      ipv4_addr: 10.30.50.10
      groups:
        - nintendo_switches
    nintendo-switch-2:
      hostname: nintendo-switch-2
      mac_addr: 48:a5:e7:79:07:ef
      network: vlan_wireless
      dhcp_client: true
      ipv4_addr: 10.30.50.11
      groups:
        - nintendo_switches
    nvidia_shield_tv_livingroom:
      hostname: nvidia_shield_tv_livingroom
      mac_addr: 00:04:4b:83:12:01
      network: vlan_wireless
      dhcp_client: true
      ipv4_addr: 10.30.50.12
      groups:
        - media_players
        - nvidia_shields
    nvidia_shield_tv_basement:
      hostname: nvidia_shield_tv_basement
      mac_addr: 48:b0:2d:13:b7:a0
      network: vlan_wireless
      dhcp_client: true
      ipv4_addr: 10.30.50.13
      groups:
        - media_players
        - nvidia_shields
    nvidia_shield_tv_masterbedroom:
      hostname: nvidia_shield_tv_masterbedroom
      mac_addr: 48:b0:2d:13:b7:a1
      network: vlan_wireless
      dhcp_client: true
      ipv4_addr: 10.30.50.14
      groups:
        - media_players
        - nvidia_shields
    firetv_bar_tv:
      hostname: firetv_bar_tv
      mac_addr: 74:ec:b2:5a:c3:47
      network: vlan_wireless
      dhcp_client: true
      ipv4_addr: 10.30.50.15
      groups:
        - media_players
    hdhr:
      hostname: hdhr
      mac_addr: 00:18:dd:04:cb:77
      network: vlan_wireless
      dhcp_client: true
      ipv4_addr: 10.30.50.70
      groups:
        - media_players
        - hd_homeruns
    google_home_mini_ryanoffice:
      hostname: google_home_mini_ryanoffice
      mac_addr: 30:fd:38:75:0f:a1
      network: vlan_wireless
      dhcp_client: true
      ipv4_addr: 10.30.50.112
      groups:
        - media_players
        - google_device
    google_home_kitchendisplay:
      hostname: google_home_kitchendisplay
      mac_addr: a4:77:33:f2:65:38
      network: vlan_wireless
      dhcp_client: true
      ipv4_addr: 10.30.50.114
      groups:
        - media_players
        - google_device
    sonos_kitchen:
      hostname: sonos_kitchen
      mac_addr: 34:7e:5c:1e:04:82
      network: vlan_wireless
      dhcp_client: true
      ipv4_addr: 10.30.50.150
      groups:
        - media_players
        - sonos_players
    sonos_upstairs_hallway:
      hostname: sonos_upstairs_hallway
      mac_addr: 5c:aa:fd:4e:d2:9e
      network: vlan_wireless
      dhcp_client: true
      ipv4_addr: 10.30.50.151
      groups:
        - media_players
        - sonos_players
    sonos_livingroom:
      hostname: sonos_livingroom
      mac_addr: 5c:aa:fd:4e:d6:24
      network: vlan_wireless
      dhcp_client: true
      ipv4_addr: 10.30.50.152
      groups:
        - media_players
        - sonos_players
    sonos_bar:
      hostname: sonos_bar
      mac_addr: 34:7e:5c:1e:04:4c
      network: vlan_wireless
      dhcp_client: true
      ipv4_addr: 10.30.50.153
      groups:
        - media_players
        - sonos_players
    sonos_move:
      hostname: sonos_move
      mac_addr: 48:a6:b8:e0:cd:ec
      network: vlan_wireless
      dhcp_client: true
      ipv4_addr: 10.30.50.154
      groups:
        - media_players
        - sonos_players
    sonos_office:
      hostname: sonos_office
      mac_addr: 48:a6:b8:68:81:b5
      network: vlan_wireless
      dhcp_client: true
      ipv4_addr: 10.30.50.155
      groups:
        - media_players
        - sonos_players
    sonos_livingroom_tv:
      hostname: sonos_livingroom_tv
      mac_addr: 48:a6:b8:68:81:b9
      network: vlan_wireless
      dhcp_client: true
      ipv4_addr: 10.30.50.156
      groups:
        - media_players
        - sonos_players
    sonos_masterbedroom_tv:
      hostname: sonos_masterbedroom_tv
      mac_addr: 48:a6:b8:68:81:b2
      network: vlan_wireless
      dhcp_client: true
      ipv4_addr: 10.30.50.157
      groups:
        - media_players
        - sonos_players
    lg_basement_tv:
      hostname: lg_basement_tv
      mac_addr: 20:3d:bd:6b:24:d2
      network: vlan_wireless
      dhcp_client: true
      ipv4_addr: 10.30.50.170
      groups:
        - media_players
        - lg_tvs

  services:
    k8s_api:
      ipv4_addr: 10.45.10.10
    k8s_promtail:
      ipv4_addr: 10.45.10.16
    k8s_unifi:
      ipv4_addr: 10.45.10.17
    k8s_ingress:
      ipv4_addr: 10.45.20.10
    k8s_plex:
      ipv4_addr: 10.45.100.100
    k8s_mqtt:
      ipv4_addr: 10.45.10.11
  static_mappings:
    - hostname: k8s.holthome.net
      service: k8s_api
    - hostname: unifi
      service: k8s_unifi
