---
address_book:
  hosts:
    ########################
    ### Non-DHCP Clients ###
    ########################
    fw:
      hostname: fw
      network: servers
      dhcp_client: false
      ipv4_hostid: 1
      groups:
        - fw
    cp-0:
      hostname: cp-0
      network: servers
      dhcp_client: false
      ipv4_addr: 10.20.0.20
      groups:
        - k8s_nodes
        - sonos_controllers
        - media_players
    cp-1:
      hostname: cp-1
      network: servers
      dhcp_client: false
      ipv4_addr: 10.20.0.21
      groups:
        - k8s_nodes
        - sonos_controllers
        - media_players
    cp-2:
      hostname: cp-2
      network: servers
      dhcp_client: false
      ipv4_addr: 10.20.0.22
      groups:
        - k8s_nodes
        - sonos_controllers
        - media_players
    nas-0:
      hostname: nas-0
      network: servers
      aliases:
        - nas.holthome.net
      dhcp_client: false
      ipv4_addr: 10.20.0.10
      groups:
        - nas_nodes
    nas-0-ipmi:
      hostname: nas-0-ipmi
      network: mgmt
      dhcp_client: false
      ipv4_addr: 10.9.18.10
      groups:
        - ipmi
    nas-1:
      hostname: nas-1
      network: servers
      dhcp_client: false
      ipv4_addr: 10.20.0.11
      groups:
        - nas_nodes
    nas-1-ipmi:
      hostname: nas-1-ipmi
      network: mgmt
      dhcp_client: false
      ipv4_addr: 10.9.18.11
      groups:
        - ipmi
    node-0:
      hostname: node-0
      network: servers
      dhcp_client: false
      ipv4_addr: 10.20.10.20
      groups:
        - k8s_nodes
        - sonos_controllers
        - media_players
    node-0-ipmi:
      hostname: node-0-ipmi
      network: mgmt
      dhcp_client: false
      ipv4_addr: 10.9.18.20
      groups:
        - ipmi
    node-1:
      hostname: node-1
      network: servers
      dhcp_client: false
      ipv4_addr: 10.20.10.21
      groups:
        - k8s_nodes
        - sonos_controllers
        - media_players
    node-1-ipmi:
      hostname: node-1-ipmi
      network: mgmt
      dhcp_client: false
      ipv4_addr: 10.9.18.21
      groups:
        - ipmi
    node-2:
      hostname: node-2
      network: servers
      dhcp_client: false
      ipv4_addr: 10.20.10.22
      groups:
        - k8s_nodes
        - sonos_controllers
        - media_players
    node-2-ipmi:
      hostname: node-2-ipmi
      network: mgmt
      dhcp_client: false
      ipv4_addr: 10.9.18.22
      groups:
        - ipmi
    node-3:
      hostname: node-3
      network: servers
      dhcp_client: false
      ipv4_addr: 10.20.10.23
      groups:
        - k8s_nodes
        - sonos_controllers
        - media_players
    node-3-ipmi:
      hostname: node-3-ipmi
      network: mgmt
      dhcp_client: false
      ipv4_addr: 10.9.18.23
      groups:
        - ipmi
    pki:
      hostname: pki
      network: servers
      dhcp_client: false
      ipv4_addr: 10.20.0.15
      groups:
        - pki
    sm-0:
      hostname: sm-0
      network: servers
      dhcp_client: false
      ipv4_addr: 10.20.10.18
      groups:
        - utility
    3com:
      hostname: 3com
      network: mgmt
      dhcp_client: false
      ipv4_addr: 10.9.18.254
      groups:
        - networking
    apc-ups:
      hostname: apc-ups
      network: mgmt
      dhcp_client: false
      ipv4_addr: 10.9.18.245
      groups:
        - apc
        - snmp_nodes

    ####################
    ### DHCP Clients ###
    ####################
    ubnt-upstairs:
      hostname: ubnt-upstairs
      mac_addr: 80:2a:a8:10:ed:da
      network: mgmt
      dhcp_client: true
      ipv4_addr: 10.9.18.100
      groups:
        - unifi_devices
    ubnt-basement:
      hostname: ubnt-basement
      mac_addr: 80:2a:a8:56:70:a4
      network: mgmt
      dhcp_client: true
      ipv4_addr: 10.9.18.101
      groups:
        - unifi_devices
    ubnt-10gbswitch:
      hostname: ubnt-10gbswitch
      mac_addr: b4:fb:e4:56:cf:8e
      network: mgmt
      dhcp_client: true
      ipv4_addr: 10.9.18.102
      groups:
        - unifi_devices
    ubnt-16poeswitch:
      hostname: ubnt-16poeswitch
      mac_addr: b4:fb:e4:1c:a1:f6
      network: mgmt
      dhcp_client: true
      ipv4_addr: 10.9.18.103
      groups:
        - unifi_devices
    ap-patio:
      hostname: ap-patio
      mac_addr: 00:31:92:8a:7e:ee
      network: mgmt
      dhcp_client: true
      ipv4_addr: 10.9.18.105
      groups:
        - tplink_eap_devices

    # bcs:
    #   hostname: bcs
    #   mac_addr: aa:00:02:00:24:0f
    #   network: wired
    #   dhcp_client: true
    #   ipv4_addr: 10.9.18.50
    #   groups:
    #     - bcs
    rydesk:
      hostname: rydesk
      mac_addr: 7e:c9:9f:f0:08:15
      network: wired
      dhcp_client: true
      ipv4_addr: 10.10.0.200
      groups:
        - sonos_controllers
        - nfs_clients
        - smb_clients
        - plex_clients
        - print_clients
        - mgmt_nodes

    Ryan-PC:
      hostname: Ryan-PC
      mac_addr: 52:54:00:f5:e6:19
      network: wired
      dhcp_client: true
      ipv4_addr: 10.10.0.198
      groups:
        - sonos_controllers
        - nfs_clients
        - smb_clients
        - plex_clients
        - print_clients
        - mgmt_nodes

    hp_printer:
      hostname: hp_printer
      mac_addr: f8:0d:ac:7b:d9:90
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.5
      groups:
        - printers
        - smb_clients
    nintendo-switch-1:
      hostname: nintendo-switch-1
      mac_addr: 58:2f:40:7c:25:19
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.10
      groups:
        - nintendo_switches
    nintendo-switch-2:
      hostname: nintendo-switch-2
      mac_addr: 48:a5:e7:79:07:ef
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.11
      groups:
        - nintendo_switches
    nvidia_shield_tv_livingroom:
      hostname: nvidia_shield_tv_livingroom
      mac_addr: 00:04:4b:83:12:01
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.12
      groups:
        - media_players
        - nvidia_shields
        - plex_clients
        - android_tvs
        - chromecast_players
        - airplay_devices
    nvidia_shield_tv_basement:
      hostname: nvidia_shield_tv_basement
      mac_addr: 48:b0:2d:13:b7:a0
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.13
      groups:
        - media_players
        - nvidia_shields
        - plex_clients
        - android_tvs
        - chromecast_players
        - airplay_devices
    nvidia_shield_tv_masterbedroom:
      hostname: nvidia_shield_tv_masterbedroom
      mac_addr: 48:b0:2d:13:d1:d6
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.14
      groups:
        - media_players
        - nvidia_shields
        - plex_clients
        - android_tvs
        - chromecast_players
        - airplay_devices
    firetv_bar_tv:
      hostname: firetv_bar_tv
      mac_addr: 74:ec:b2:5a:c3:47
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.15
      groups:
        - media_players
        - android_tvs
        - chromecast_players
    hdhr:
      hostname: hdhr
      mac_addr: 00:18:dd:04:cb:77
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.70
      groups:
        - media_players
        - hd_homeruns
    google_home_mini_ryanoffice:
      hostname: google_home_mini_ryanoffice
      mac_addr: 30:fd:38:75:0f:a1
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.112
      groups:
        - media_players
        - google_device
    google_home_kitchendisplay:
      hostname: google_home_kitchendisplay
      mac_addr: a4:77:33:f2:65:38
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.114
      groups:
        - media_players
        - google_device
    sonos_kitchen-1:
      hostname: sonos_kitchen_1
      mac_addr: 34:7e:5c:1e:04:82
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.150
      groups:
        - media_players
        - sonos_players
        - airplay_devices
    sonos_kitchen-2:
      hostname: sonos_kitchen_2
      mac_addr: 34:7e:5c:1e:04:4c
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.158
      groups:
        - media_players
        - sonos_players
        - airplay_devices
    sonos_upstairs_hallway:
      hostname: sonos_upstairs_hallway
      mac_addr: 5c:aa:fd:4e:d2:9e
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.151
      groups:
        - media_players
        - sonos_players
        - airplay_devices
    sonos_basement:
      hostname: sonos_basement
      mac_addr: 5c:aa:fd:4e:d6:24
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.152
      groups:
        - media_players
        - sonos_players
        - airplay_devices
    sonos_bar:
      hostname: sonos_bar
      mac_addr: 48:a6:b8:f9:11:b6
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.153
      groups:
        - media_players
        - sonos_players
        - airplay_devices
    sonos_move:
      hostname: sonos_move
      mac_addr: 48:a6:b8:e0:cd:ec
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.154
      groups:
        - media_players
        - sonos_players
        - airplay_devices
    sonos_office:
      hostname: sonos_office
      mac_addr: 48:a6:b8:68:81:b5
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.155
      groups:
        - media_players
        - sonos_players
        - airplay_devices
    sonos_livingroom_tv:
      hostname: sonos_livingroom_tv
      mac_addr: 54:2a:1b:87:58:10
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.156
      groups:
        - media_players
        - sonos_players
        - airplay_devices
    sonos_masterbedroom_tv:
      hostname: sonos_masterbedroom_tv
      mac_addr: 48:a6:b8:b3:9f:e7
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.157
      groups:
        - media_players
        - sonos_players
        - airplay_devices
    lg_basement_tv:
      hostname: lg_basement_tv
      mac_addr: 20:3d:bd:6b:24:d2
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.170
      groups:
        - media_players
        - lg_tvs
    lg_masterbedroom_tv:
      hostname: lg_masterbedroom_tv
      mac_addr: ac:f1:08:59:b5:46
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.171
      groups:
        - media_players
        - lg_tvs
    Ryans-iPad:
      hostname: Ryans-iPad
      mac_addr: 80:d6:05:3b:32:20
      network: wireless
      dhcp_client: true
      ipv4_addr: 10.30.50.240
      groups:
        - sonos_controllers
        - media_players
        - print_clients
    Ryans-iPhone:
      hostname: Ryans-iPhone
      mac_addr: 5c:52:30:2b:6a:f7
      network: wireless
      dhcp_client: true
      ipv4_addr: 10.30.50.200
      groups:
        - sonos_controllers
        - media_players
        - print_clients
        - smb_clients
        - homekit_clients
        - verizon_wifi_calling
        - chromecast_clients
        - ecobee_clients
        - plex_clients
        - airplay_clients
    rybook:
      hostname: rybook
      mac_addr: 74:42:8b:68:50:fe
      network: wireless
      dhcp_client: true
      ipv4_addr: 10.30.50.250
      groups:
        - sonos_controllers
        - media_players
        - smb_clients
        - print_clients
    StefaniesiPhone:
      hostname: StefaniesiPhone
      mac_addr: 88:b9:45:32:84:e4
      network: wireless
      dhcp_client: true
      ipv4_addr: 10.30.50.201
      groups:
        - sonos_controllers
        - media_players
        - print_clients
        - smb_clients
        - homekit_clients
        - verizon_wifi_calling
        - chromecast_clients
        - ecobee_clients
        - plex_clients
        - airplay_clients
    Steffi-PC:
      hostname: Steffi-PC
      mac_addr: 50:1a:c5:e9:75:af
      network: wireless
      dhcp_client: true
      ipv4_addr: 10.30.50.251
      groups:
        - sonos_controllers
        - media_players
        - smb_clients
        - print_clients
    Caydans-iPad:
      hostname: Caydans-iPad
      mac_addr: 10:00:20:33:a3:84
      network: wireless
      dhcp_client: true
      ipv4_addr: 10.30.50.202
      groups:
        - media_players
        - print_clients
        - plex_clients
    ecobee:
      hostname: ecobee
      mac_addr: 44:61:32:f0:99:8b
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.180
      groups:
        - ecobee
        - homekit_devices
    zigbee-controller:
      hostname: zigbee-controller
      mac_addr: 94:b9:7e:6b:bb:d3
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.185
      groups:
        - zigbee_controllers
    miele-dishwasher:
      hostname: miele-dishwasher
      mac_addr: 00:1d:63:27:64:45
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.186
      groups:
        - miele_dishwashers
    energy-meter:
      hostname: energy-meter
      mac_addr: 3c:61:05:2a:e4:a0
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.200
      groups:
        - esphome_devices
    utility-closet-sensors:
      hostname: utility-closet-sensors
      mac_addr: 7c:9e:bd:f5:2e:b0
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.201
      groups:
        - esphome_devices
    sunroom-corner-lights:
      hostname: sunroom-corner-lights
      mac_addr: e8:68:e7:f1:5a:c3
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.202
      groups:
        - esphome_devices
    front-under-bar-lights:
      hostname: front-under-bar-lights
      mac_addr: 84:cc:a8:af:a2:ca
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.203
      groups:
        - esphome_devices
    garage-front-lights:
      hostname: garage_front_lights
      mac_addr: 68:c6:3a:fb:70:ae
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.204
      groups:
        - esphome_devices
    patio-door-lights:
      hostname: patio-door-lights
      mac_addr: 68:c6:3a:fb:42:b6
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.205
      groups:
        - esphome_devices
    well-switch:
      hostname: well-switch
      mac_addr: dc:4f:22:4c:98:98
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.206
      groups:
        - esphome_devices
    master-bathroom-counter-light:
      hostname: master-bathroom-counter-light
      mac_addr: e8:68:e7:f0:45:cd
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.207
      groups:
        - esphome_devices
    garage-door:
      hostname: garage-door
      mac_addr: e8:db:84:d4:cd:53
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.208
      groups:
        - esphome_devices
    porch-ceiling-lights:
      hostname: porch-ceiling-lights
      mac_addr: 68:c6:3a:fb:67:e3
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.209
      groups:
        - esphome_devices
    garage-side-lights:
      hostname: garage-side-lights
      mac_addr: 68:c6:3a:fb:3b:78
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.210
      groups:
        - esphome_devices
    sunroom-window-lights:
      hostname: sunroom-window-lights
      mac_addr: 3c:61:05:eb:e0:29
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.211
      groups:
        - esphome_devices
    lifx-bar-ceiling-1:
      hostname: lifx-bar-ceiling-1
      mac_addr: d0:73:d5:20:16:2a
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.190
      groups:
        - lifx_devices
        - homekit_devices
    lifx-bar-ceiling-2:
      hostname: lifx-bar-ceiling-2
      mac_addr: d0:73:d5:20:18:7d
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.191
      groups:
        - lifx_devices
        - homekit_devices
    lifx-bar-ceiling-3:
      hostname: lifx-bar-ceiling-3
      mac_addr: d0:73:d5:20:24:d5
      network: iot
      dhcp_client: true
      ipv4_addr: 10.40.50.192
      groups:
        - lifx_devices
        - homekit_devices

    camera_backpatio:
      hostname: camera_backpatio
      mac_addr: 58:50:ed:2d:47:4b
      network: video
      dhcp_client: true
      ipv4_addr: 10.50.50.100
      groups:
        - rtsp
    amcrest_frontdoor:
      hostname: amcrest_frontdoor
      mac_addr: 9c:8e:cd:30:99:4d
      network: video
      dhcp_client: true
      ipv4_addr: 10.50.50.101
      groups:
        - rtsp
        - amcrest_cameras

  services:
    k8s_api:
      ipv4_addr: 10.45.10.10
    k8s_promtail:
      ipv4_addr: 10.45.10.16
    k8s_unifi:
      ipv4_addr: 10.45.10.17
    k8s_ingress:
      ipv4_addr: 10.45.20.10
    k8s_plex:
      ipv4_addr: 10.45.100.100
    k8s_mqtt:
      ipv4_addr: 10.45.10.11
    k8s_dns:
      ipv4_addr: 10.45.10.13
    k8s_tplink_controller:
      ipv4_addr: 10.45.10.20
    mullvad_ip:
      ipv4_addr: 198.54.132.82 
    racknerd_ip:
      ipv4_addr: 173.82.197.179
  static_mappings:
    - hostname: k8s.holthome.net
      service: k8s_api
    - hostname: unifi
      service: k8s_unifi
