- name: Ensure External-Secrets Azure Secret Created
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: external-secrets-azure-credentials
        namespace: kube-system
      data:
        tenantid: "{{ EXTERNAL_SECRETS_AZURE_CREDENTIALS_TENANTID }}"
        clientid: "{{ EXTERNAL_SECRETS_AZURE_CREDENTIALS_CLIENTID }}"
        clientsecret: "{{ EXTERNAL_SECRETS_AZURE_CREDENTIALS_CLIENTSECRET }}"
