---
- name: check os_family support
  assert:
    that:
      - ansible_os_family | lower in longhorn_supported_os_families
    fail_msg:
      - "os_family '{{ ansible_os_family }}' is not supported at this time"

- name: 'validate variable : longhorn_enabled'
  assert:
    that:
      - longhorn_enabled | type_debug == 'bool'
    fail_msg:
      - "Variable 'longhorn_enabled' should be of type 'bool'"
      - 'Type is: {{ longhorn_enabled | type_debug }}'
      - "Value is: {{ longhorn_enabled | default('undefined') }}"

- name: 'validate variable : nfs_enabled'
  assert:
    that:
      - nfs_enabled | type_debug == 'bool'
    fail_msg:
      - "Variable 'nfs_enabled' should be of type 'bool'"
      - 'Type is: {{ nfs_enabled | type_debug }}'
      - "Value is: {{ nfs_enabled | default('undefined') }}"

- name: 'validate variable : zfs_enabled'
  assert:
    that:
      - zfs_enabled | type_debug == 'bool'
    fail_msg:
      - "Variable 'zfs_enabled' should be of type 'bool'"
      - 'Type is: {{ zfs_enabled | type_debug }}'
      - "Value is: {{ zfs_enabled | default('undefined') }}"
