---
- name: set facts for ansible ssh
  set_fact:
    ansible_connection: ssh
    
- name: get address-group file contents from remote
  ansible.builtin.slurp:
    src: "{{ item['from_file'] }}"
  with_items:
    - "{{ firewall_address_groups }}"
  when:
    - item['from_file'] is defined
  register: remote_address_files

- name: set facts for network connection
  set_fact:
    ansible_connection: ansible.netcommon.network_cli

- name: store vyos_managed_address_groups
  vars:
    address_group_files: "{{ remote_address_files['results'] | rejectattr('skipped', 'defined') }}"
  ansible.builtin.set_fact:
    vyos_managed_address_groups: "{{ lookup('template', './config/address-groups.j2') | from_yaml }}"

- name: get current firewall configuration
  vyos.vyos.vyos_firewall_global:
    config:
    state: gathered
  register: vyos_firewall_config

- name: configure address groups
  vars:
    config: "{{ vyos_firewall_config['gathered'].copy() }}"
    firewall_groups: "{{ {'address_group': vyos_managed_address_groups} }}"
  vyos.vyos.vyos_firewall_global:
    config: "{{ lookup('template', './config/firewall-groups.j2') | from_yaml }}"
    state: replaced
