---
- name: store vyos_managed_firewall_rulesets_ipv4
  vars:
    zone_rules: "{{ firewall_global_rules | combine(firewall_rules) }}"
  ansible.builtin.set_fact:
    vyos_managed_firewall_rulesets_ipv4: "{{ lookup('template', './config/firewall-rules.j2') | from_yaml }}"

- name: configure ipv4 firewall rules
  vyos.vyos.vyos_firewall_rules:
    config:
    - afi: ipv4
      rule_sets: "{{ vyos_managed_firewall_rulesets_ipv4 }}"
    state: replaced
  register: result_vyos_managed_firewall_rulesets_ipv4
