all:
master:
  hosts:
    h2-0:
      ansible_host: h2-0.holthome.net
  vars:
    k3s_control_node: true
    k3s_tls_san: "k8s.holthome.net"

nodes:
  hosts:
    r610-0:
      ansible_host: r610-0.holthome.net
    r610-1:
      ansible_host: r610-1.holthome.net
    r610-2:
      ansible_host: r610-2.holthome.net
    r720-0:
      ansible_host: r720-0.holthome.net
    # n2-0:
    #   ansible_host: n2-0.holthome.net

longhorn:
  hosts:
    r610-0:
      ansible_host: r610-0.holthome.net
    r610-1:
      ansible_host: r610-1.holthome.net
    r610-2:
      ansible_host: r610-2.holthome.net
  vars:
    lvm_groups:
      - vgname: longhorn-vg
        disks:
          - /dev/sdb
          - /dev/sdc
          - /dev/sdd
        opts: i3
        create: true
        lvnames:
          - lvname: lv0
            size: 100%FREE
            create: true
            filesystem: ext4
            mount: true
            mntp: /var/lib/longhorn
    manage_lvm: true

nfs:
  hosts:
    r720-0:
      ansible_host: r720-0.holthome.net
  vars:
    nfs_exports:
      - /mnt/tank/share 10.20.0.0/16(rw,async,no_subtree_check,no_root_squash)

# arm:
#   hosts:
#     n2-0:
#       ansible_host: n2-0.holthome.net

k3s_cluster:
  children:
    master:
    nodes:

storage:
  children:
    ceph:
    nfs:

vault:
  hosts:
    localhost:
      ansible_connection: local

vyos:
  hosts:
    vyos:
      ansible_host: 10.20.0.1
