# -------------------------
# Firewall zone definition
# -------------------------

vyos_firewall_zones:
  - name: wan
    description: WAN zone
    interfaces:
      - wan
    fw_policies:
      - includeZones:
          - video
        default: drop
        defaultLog: true
        rules:
          - accept_amcrest_to_amcrest_cloud_udp: true
          - accept_amcrest_to_amcrest_cloud_tcp: true
      - includeZones:
          - wireless
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_http: null
          - accept_https: null
          - accept_wifi_calling_from_ios_devices: null
      - includeZones:
          - iot
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_http: null
          - accept_https: null
          - accept_ecobee_ems_from_ecobee: null
      - includeZones:
          - servers
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_dns: null
          - accept_http: null
          - accept_https: null
          - accept_racknerd_vpn_from_k8s_nodes: null
          - accept_mullvad_vpn_from_k8s_nodes: null
      - ignoreZones:
          - video
          - wireless
          - iot
          - servers
        default: accept
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
  - name: local
    description: Local router zone
    local: true
    fw_policies:
      - includeZones:
          - mgmt
        default: drop
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_ssh: null
          - accept_dns: null
          - accept_ntp: null
          - accept_dhcp: null
      - includeZones:
          - wired
          - wg_trusted
        default: drop
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_icmp: null
          - accept_ssh: null
          - accept_dns: null
          - accept_ntp: null
          - accept_dhcp: null
          - accept_igmp: null
          - accept_mdns: null
          - accept_discovery_from_sonos_players: null
          - accept_discovery_from_sonos_controllers: null
      - includeZones:
          - iot
        default: drop
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_dns: null
          - accept_ntp: null
          - accept_dhcp: null
          - accept_igmp: null
          - accept_mdns: null
          - accept_discovery_from_sonos_players: null
          - accept_discovery_from_sonos_controllers: null
          - accept_discovery_from_hass: null
      - includeZones:
          - video
        default: drop
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_dns: null
          - accept_ntp: null
          - accept_dhcp: null
      - includeZones:
          - servers
        default: drop
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_dns: null
          - accept_mdns: null
          - accept_ntp: null
          - accept_dhcp: null
          - accept_bgp: null
          - accept_discovery_from_hass: null
          - accept_node_exporter_from_k8s_nodes: null
          # - accept_prometheus_from_k8s_nodes: null
      - includeZones:
          - wan
        default: drop
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_wireguard: null
      - includeZones:
          - wireless
        default: drop
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_dns: null
          - accept_mdns: null
          - accept_dhcp: null
          - accept_discovery_from_sonos_controllers: null
          - accept_ssh: null
      - ignoreZones:
          - mgmt
          - wired
          - wg_trusted
          - iot
          - video
          - servers
          - wan
          - wireless
        default: drop
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_dns: null
          - accept_ntp: null
          - accept_dhcp: null
  - name: mgmt
    description: Management zone
    interfaces:
      - mgmt
      - rescue
    fw_policies:
      - includeZones:
          - wired
          - wg_trusted
        default: accept
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
      - includeZones:
          - servers
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_snmp_to_snmp_nodes_from_k8s_nodes: null
      - ignoreZones:
          - wired
          - wg_trusted
          - servers
        default: drop
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
  - name: servers
    description: Server iot zone
    interfaces:
      - servers
    fw_policies:
      - includeZones:
          - wired
          - wg_trusted
        default: accept
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_icmp: null
          - accept_ssh: null
          # - accept_mqtt: null
          - accept_k8s_api: null
          - accept_k8s_ingress_from_internal: null
          - accept_k8s_ingress_from_internal: null
          - accept_plex_from_internal_tcp: null
          - accept_plex_from_internal_udp: null
          - accept_smb_from_smb_clients: null
          - accept_nfs_from_smb_clients: null
          - accept_stepca_ingress_from_internal: null
      - includeZones:
          - wan
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_ingress_from_cloudflare: null
          - accept_plex_from_external: null
      - includeZones:
          - mgmt
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_icmp: null
          - accept_k8s_api: null
          - accept_dns: null
          - accept_k8s_ingress_from_internal: null
          - accept_ssh: null
          - accept_unifi_inform: null
          - accept_unifi_stun: null
          - accept_stepca_ingress_from_internal: null
      - includeZones:
          - wireless
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_icmp: null
          - accept_k8s_api: null
          - accept_dns: null
          - accept_plex_from_internal_tcp: null
          - accept_plex_from_internal_udp: null
          - accept_k8s_ingress_from_internal: null
          - accept_homekit_from_ios_devices_to_k8s_nodes_tcp: null
          - accept_homekit_from_ios_devices_to_k8s_nodes_udp: null
      - includeZones:
          - iot
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_dns: null
          # - accept_mqtt: null
          - accept_plex_from_internal_tcp: null
          - accept_plex_from_internal_udp: null
          - accept_smb_from_smb_clients: null
          - accept_hdhr_to_media_players: null
          - accept_k8s_ingress_from_sonos_players: null
          # - accept_k8s_ingress_from_wall_displays: null
          # - accept_k8s_ingress_from_sonos_players: null
      - includeZones:
          - video
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_dns: null
      - includeZones:
          - local
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_bgp: null
          - accept_mdns: null
          - accept_k8s_api: null
          - accept_promtail_syslog: null
          - accept_discovery_from_sonos_players: null
          - accept_discovery_from_sonos_controllers: null
          - accept_dns: null
      - ignoreZones:
          - wired
          - wg_trusted
          - wan
          - mgmt
          - wireless
          - iot
          - local
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
  - name: wired
    description: Trusted iot zone
    interfaces:
      - wired
    fw_policies:
      - includeZones:
          - local
        default: drop
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_igmp: null
          - accept_mdns: null
          - accept_discovery_from_sonos_players: null
      - includeZones:
          - servers
        default: drop
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_mdns: null
          - accept_resilio_from_k8s_nodes: null
      - includeZones:
          - wg_trusted
        default: accept
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
      - includeZones:
          - iot
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_udp_from_sonos_players_to_sonos_controllers: null
          - accept_tcp_from_sonos_players_to_sonos_controllers: null
      - ignoreZones:
          - local
          - servers
          - wg_trusted
          - iot
        default: drop
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
  - name: wireless
    description: Guest iot zone
    interfaces:
      - wireless
    fw_policies:
      - includeZones:
          - servers
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_icmp: null
          - accept_resilio_from_k8s_nodes: null
      - includeZones:
          - local
        default: drop
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_igmp: null
          - accept_mdns: null
          - accept_discovery_from_sonos_players: null
      - includeZones:
          - iot
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_icmp: null
          - accept_udp_from_sonos_players_to_sonos_controllers: null
          - accept_tcp_from_sonos_players_to_sonos_controllers: null
      - ignoreZones:
          - servers
          - local
          - iot
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
  - name: iot
    description: iot iot zone
    interfaces:
      - iot
    fw_policies:
      - includeZones:
          - wired
          - wg_trusted
          - wireless
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_icmp: null
          - accept_app_control_from_sonos_controllers_tcp: null
          - accept_app_control_from_sonos_controllers_udp: null
          - accept_media_players_to_hdhr: null
          - accept_chromecast_to_chromecast_players_from_chromecast_clients: null
      - includeZones:
          - servers
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_icmp: null
          - accept_esphome_from_k8s_nodes: null
          - accept_homekit_from_k8s_nodes: null
          - accept_android_adb_from_k8s_nodes: null
          - accept_app_control_from_sonos_controllers_tcp: null
          - accept_app_control_from_sonos_controllers_udp: null
          - accept_media_players_to_hdhr: null
          - accept_plex_to_media_players: null
          - accept_k8s_nodes_to_poe_zigbee_controller: null
          - accept_lg_remote_to_lg_tvs_from_k8s_nodes: null
          # - accept_k8s_nodes: null
      - includeZones:
          - local
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_igmp: null
          - accept_mdns: null
          - accept_discovery_from_sonos_controllers: null
      - ignoreZones:
          - wired
          - wg_trusted
          - wireless
          - servers
          - local
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
  - name: video
    description: Video iot zone
    interfaces:
      - video
    fw_policies:
      - includeZones:
          - mgmt
          - wired
          - wg_trusted
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_icmp: null
          - accept_http: null
          - accept_https: null
      - includeZones:
          - servers
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_icmp: null
          - accept_http: null
          - accept_https: null
          - accept_rtsp_from_k8s_nodes: null
          # - accept_k8s_nodes: null
      - ignoreZones:
          - mgmt
          - wired
          - wg_trusted
          - servers
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
  - name: wg_trusted
    description: Wireguard VPN trusted iot
    interfaces:
      - wg_trusted
    fw_policies:
      - includeZones:
          - local
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_igmp: null
          - accept_mdns: null
      - ignoreZones:
          - local
        default: drop
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
