# -------------------------
# Firewall Rule definition
# -------------------------

vyos_firewall_rules:
  accept_wireguard:
    action: accept
    protocol: udp
    destination:
      port: "{{ vyos_wireguard['servers']['wg_trusted']['port'] }}"

  accept_k8s_api:
    action: accept
    log: true
    protocol: tcp
    destination:
      port: 6443

  accept_ingress_from_cloudflare:
    action: accept
    protocol: tcp
    source:
      network-group: cloudflare-ipv4
    destination:
      port: http,https
      address-group: k8s_ingress

  accept_mqtt:
    action: accept
    protocol: tcp
    destination:
      port: 1883
      address-group: k8s_mqtt
    source:
      address-group: mqtt_devices

  accept_k8s_nodes:
    action: accept
    log: true
    protocol: tcp
    source:
      address-group: k8s_nodes

  accept_unifi_inform:
    action: accept
    protocol: tcp
    source:
      address-group: unifi_devices
    destination:
      port: 8080
      address-group: k8s_unifi

  accept_unifi_stun:
    action: accept
    protocol: udp
    source:
      address-group: unifi_devices
    destination:
      port: 3478
      address-group: k8s_unifi

  accept_promtail_syslog:
    action: accept
    protocol: tcp
    destination:
      port: 1514
      address-group: k8s_promtail

  accept_prometheus_from_k8s_nodes:
    action: accept
    protocol: tcp
    source:
      address-group: k8s_nodes
    destination:
      port: 9153

  accept_k8s_ingress_from_wall_displays:
    action: accept
    protocol: tcp
    source:
      address-group: wall_displays
    destination:
      port: http,https
      address-group: k8s_ingress

  accept_plex_from_external:
    action: accept
    protocol: tcp
    destination:
      port: 32400
      address-group: k8s_plex

  accept_plex_from_internal_tcp:
    action: accept
    protocol: tcp
    source:
      address-group: plex_clients
    destination:
      port: 32400,5353,32469
      address-group: k8s_plex

  accept_plex_from_internal_udp:
    action: accept
    protocol: udp
    source:
      address-group: plex_clients
    destination:
      port: 1900,5353,8324,32410,32412,32413,32414
      address-group: k8s_plex

  accept_discovery_from_hass:
    action: accept
    protocol: udp
    source:
      address-group: k8s_nodes
    destination:
      port: 1900

  accept_discovery_from_sonos_players:
    action: accept
    protocol: udp
    source:
      address-group: sonos_players
    destination:
      port: 1900,1901

  accept_discovery_from_sonos_controllers:
    action: accept
    protocol: udp
    source:
      address-group: sonos_controllers
    destination:
      port: 1900,1901,57621

  accept_udp_from_sonos_players_to_sonos_controllers:
    action: accept
    protocol: udp
    source:
      address-group: sonos_players
    destination:
      address-group: sonos_controllers
      port: 30000-65535

  accept_tcp_from_sonos_players_to_sonos_controllers:
    action: accept
    protocol: tcp
    source:
      address-group: sonos_players
    destination:
      address-group: sonos_controllers
      port: 80,443,445,1400,3400,3401,3500,4070,4444

  accept_app_control_from_sonos_controllers_tcp:
    action: accept
    protocol: tcp
    source:
      address-group: sonos_controllers
    destination:
      port: 80,443,445,1400,1443,3400,3401,3445,3500,4070,4444
      address-group: sonos_players

  accept_app_control_from_sonos_controllers_udp:
    action: accept
    protocol: udp
    source:
      address-group: sonos_controllers
    destination:
      port: 136-139,1900-1901,2869,10243,10280-10284,5353,6969
      address-group: sonos_players

  accept_k8s_ingress_from_sonos_players:
    action: accept
    protocol: tcp
    source:
      address-group: sonos_players
    destination:
      port: http,https
      address-group: k8s_ingress

  accept_k8s_ingress_from_internal:
    action: accept
    protocol: tcp
    destination:
      port: http,https
      address-group: k8s_ingress

  accept_stepca_ingress_from_internal:
    action: accept
    protocol: tcp
    destination:
      port: http,https
      address-group: pki

  accept_nfs_from_nfs_clients:
    action: accept
    protocol: tcp_udp
    source:
      address-group: nfs_clients
    destination:
      port: 111,2049
      address-group: nas_nodes

  accept_smb_from_smb_clients:
    action: accept
    protocol: tcp_udp
    source:
      address-group: smb_clients
    destination:
      port: 445
      address-group: nas_nodes

  accept_ecobee_ems_from_ecobee:
    action: accept
    protocol: tcp
    source:
      address-group: ecobee
    destination:
      port: 8089,8190

  accept_ecobee_from_ecobee_clients:
    action: accept
    protocol: tcp
    source:
      address-group: ecobee_clients
    destination:
      address-group: ecobee
      port: 34883

  accept_esphome_from_k8s_nodes:
    action: accept
    protocol: tcp
    source:
      address-group: k8s_nodes
    destination:
      port: 3232,6053,8266
      address-group: esphome_devices

  accept_homekit_from_k8s_nodes:
    action: accept
    protocol: tcp
    source:
      address-group: k8s_nodes
    destination:
      port: 80,443
      address-group: homekit_devices

  accept_homekit_from_ios_devices:
    action: accept
    protocol: tcp
    source:
      address-group: homekit_clients
    destination:
      port: 80,443
      address-group: homekit_devices

  accept_homekit_from_ios_devices_to_k8s_nodes_tcp:
    action: accept
    protocol: tcp
    source:
      address-group: homekit_clients
    destination:
      port: 21063
      address-group: k8s_nodes

  accept_homekit_from_ios_devices_to_k8s_nodes_udp:
    action: accept
    protocol: udp
    source:
      address-group: homekit_clients
    destination:
      port: 5353
      address-group: k8s_nodes

  accept_mullvad_vpn_from_k8s_nodes:
    action: accept
    protocol: udp
    source:
      address-group: k8s_nodes
    destination:
      port: 51820
      address-group: mullvad_ip

  accept_racknerd_vpn_from_k8s_nodes:
    action: accept
    protocol: udp
    source:
      address-group: k8s_nodes
    destination:
      port: 51820
      address-group: racknerd_ip

  accept_rtsp_from_k8s_nodes:
    action: accept
    protocol: tcp_udp
    source:
      address-group: k8s_nodes
    destination:
      port: 80,554,5000,8000
      address-group: rtsp

  accept_android_adb_from_k8s_nodes:
    action: accept
    protocol: tcp
    source:
      address-group: k8s_nodes
    destination:
      port: 5555,8009,8443
      address-group: android_tvs

  accept_amcrest_to_amcrest_cloud_udp:
    action: accept
    protocol: udp
    source:
      address-group: amcrest_cameras
    destination:
      port: 8800-8815

  accept_amcrest_to_amcrest_cloud_tcp:
    action: accept
    protocol: tcp
    source:
      address-group: amcrest_cameras
    destination:
      port: 9112,15301,10000,12367,15100

  accept_resilio_from_k8s_nodes:
    action: accept
    protocol: tcp
    source:
      address-group: k8s_nodes
    destination:
      port: 3000

  accept_media_players_to_hdhr:
    action: accept
    protocol: tcp_udp
    source:
      address-group: media_players
    destination:
      port: 5002,5004,65001
      address-group: hd_homeruns

  accept_hdhr_to_media_players:
    action: accept
    protocol: udp
    source:
      address-group: hd_homeruns
    destination:
      port: 33021
      address-group: media_players

  accept_plex_to_media_players:
    action: accept
    protocol: tcp
    source:
      address-group: k8s_plex
      port: 32400
    destination:
      address-group: media_players

  accept_wifi_calling_from_ios_devices:
    action: accept
    protocol: udp
    source:
      address-group: verizon_wifi_calling
    destination:
      port: 500,4500

  accept_node_exporter_from_k8s_nodes:
    action: accept
    protocol: tcp
    source:
      address-group: k8s_nodes
    destination:
      port: 9100

  accept_snmp_to_snmp_nodes_from_k8s_nodes:
    action: accept
    protocol: udp
    source:
      address-group: k8s_nodes
    destination:
      port: snmp
      address-gorup: snmp_nodes

  accept_wide_range_from_k8s:
    action: accept
    protocol: tcp
    source:
      address-group: k8s_nodes
    destination:
      port: 30000-60000

  accept_k8s_nodes_to_poe_zigbee_controller:
    action: accept
    protocol: tcp
    source:
      address-group: k8s_nodes
    destination:
      port: 6638
      address-group: zigbee_controllers

  accept_chromecast_to_chromecast_players_from_chromecast_clients:
    action: accept
    protocol: tcp
    source:
      address-group: chromecast_clients
    destination:
      port: 8009
      address-group: zigbee_controllers

  accept_lg_remote_to_lg_tvs_from_k8s_nodes:
    action: accept
    protocol: tcp
    source:
      address-group: k8s_nodes
    destination:
      port: 3000
      address-group: lg_tvs

  accept_print_clients_to_printers:
    action: accept
    protocol: tcp
    source:
      address-group: print_clients
    destination:
      port: 80,631
      address-group: printers

  accept_ubnt_cloud_from_k8s_nodes:
    action: accept
    protocol: tcp
    source:
      address-group: k8s_nodes
    destination:
      port: 8883

  accept_imaps_from_k8s_nodes:
    action: accept
    protocol: tcp
    source:
      address-group: k8s_nodes
    destination:
      port: imaps

  accept_airplay_to_airplay_devices_from_airplay_clients_tcp:
    action: accept
    protocol: tcp
    source:
      address-group: airplay_clients
    destination:
      address-group: airplay_devices
      port: 5000,7000,7100,50000,7200-17210

  accept_airplay_to_airplay_devices_from_airplay_clients_udp:
    action: accept
    protocol: udp
    source:
      address-group: airplay_clients
    destination:
      address-group: airplay_devices
      port: 7200-17210
