# -------------------------
# Firewall zone definition
# -------------------------

firewall_zones:
  - name: wan
    description: WAN zone
    interfaces:
      - wan
    fw_policies:
      - includeZones:
          - video
        default: drop
        defaultLog: true
      - includeZones:
          - wireless
        default: accept
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_ecobee_ems_from_ecobee: null
      - ignoreZones:
          - video
        default: accept
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
  - name: local
    description: Local router zone
    local: true
    fw_policies:
      - includeZones:
          - mgmt
        default: drop
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_ssh: null
          - accept_dns: null
          - accept_ntp: null
          - accept_dhcp: null
      - includeZones:
          - wired
          - wg_trusted
        default: drop
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_icmp: null
          - accept_ssh: null
          - accept_dns: null
          - accept_ntp: null
          - accept_dhcp: null
          - accept_igmp: null
          - accept_mdns: null
          - accept_discovery_from_sonos_players: null
          - accept_discovery_from_sonos_controllers: null
      - includeZones:
          - iot
        default: drop
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_ssh: null
          - accept_dns: null
          - accept_ntp: null
          - accept_dhcp: null
          - accept_igmp: null
          - accept_mdns: null
          # - accept_discovery_from_sonos_players: null
          # - accept_discovery_from_sonos_controllers: null
          # - accept_discovery_from_hass: null
      - includeZones:
          - servers
        default: drop
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_dns: null
          - accept_ntp: null
          - accept_dhcp: null
          - accept_bgp: null
          # - accept_prometheus_from_k8s_nodes: null
      - includeZones:
          - wan
        default: drop
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_wireguard: null
      - includeZones:
          - wireless
        default: drop
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_dhcp: null
      - ignoreZones:
          - mgmt
          - wireless
          - iot
          - servers
          - wired
          - wg_trusted
          - wan
        default: drop
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_dns: null
          - accept_ntp: null
          - accept_dhcp: null
  - name: mgmt
    description: Management zone
    interfaces:
      - mgmt
      - rescue
    fw_policies:
      - includeZones:
          - wired
          - wg_trusted
        default: accept
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
      - ignoreZones:
          - wired
          - wg_trusted
        default: drop
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
  - name: servers
    description: Server iot zone
    interfaces:
      - servers
    fw_policies:
      - includeZones:
          - wired
          - wg_trusted
        default: accept
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_icmp: null
          - accept_k8s_ingress_from_internal: null
      - includeZones:
          - wan
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_ingress_from_cloudflare: null
          - accept_plex_from_external: null
      - includeZones:
          - mgmt
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_icmp: null
          - accept_k8s_api: null
          - accept_dns: null
          - accept_k8s_ingress_from_internal: null
          - accept_plex_from_internal_tcp: null
          - accept_plex_from_internal_udp: null
          - accept_ssh: null
          - accept_mqtt: null
          - accept_unifi_inform: null
          - accept_unifi_stun: null
          - accept_smb_from_smb_clients: null
          - accept_nfs_from_smb_clients: null
          - accept_stepca_ingress_from_internal: null
      - includeZones:
          - wireless
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_icmp: null
          - accept_k8s_api: null
          - accept_dns: null
          - accept_plex_from_internal_tcp: null
          - accept_plex_from_internal_udp: null
          - accept_k8s_ingress_from_internal: null
      - includeZones:
          - iot
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          # - accept_mqtt: null
          # - accept_plex_from_plex_clients: null
          # - accept_k8s_ingress_from_wall_displays: null
          # - accept_k8s_ingress_from_sonos_players: null
      - includeZones:
          - local
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_bgp: null
          - accept_k8s_api: null
          - accept_promtail_syslog: null
          - accept_dns: null
      - ignoreZones:
          - wan
          - local
          - mgmt
          - iot
          - wired
          - wg_trusted
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
  - name: wired
    description: Trusted iot zone
    interfaces:
      - wired
    fw_policies:
      - includeZones:
          - local
        default: drop
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_igmp: null
          - accept_mdns: null
          - accept_discovery_from_sonos_players: null
      - includeZones:
          - wg_trusted
        default: accept
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
      - includeZones:
          - iot
        default: drop
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_app_control_from_sonos_players: null
      - ignoreZones:
          - local
          - iot
          - wg_trusted
        default: drop
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
  - name: wireless
    description: Guest iot zone
    interfaces:
      - wireless
    fw_policies:
      - includeZones:
          - servers
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_icmp: null
          - accept_esphome_from_k8s_nodes: null
          - accept_app_control_from_sonos_controllers: null
      - ignoreZones:
          - servers
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
  - name: iot
    description: iot iot zone
    interfaces:
      - iot
    fw_policies:
      - includeZones:
          - wired
          - wg_trusted
        default: accept
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_icmp: null
          - accept_app_control_from_sonos_controllers: null
      - includeZones:
          - servers
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_icmp: null
          - accept_k8s_nodes: null
      - includeZones:
          - local
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_igmp: null
          - accept_mdns: null
          - accept_discovery_from_sonos_controllers: null
      - ignoreZones:
          - local
          - servers
          - wired
          - wg_trusted
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
  - name: video
    description: Video iot zone
    interfaces:
      - video
    fw_policies:
      - includeZones:
          - wired
          - wg_trusted
        default: accept
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_icmp: null
      - includeZones:
          - servers
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_icmp: null
          # - accept_k8s_nodes: null
      - ignoreZones:
          - servers
          - wired
          - wg_trusted
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
  - name: wg_trusted
    description: Wireguard VPN trusted iot
    interfaces:
      - wg_trusted
    fw_policies:
      - includeZones:
          - local
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_igmp: null
          - accept_mdns: null
          - accept_discovery_from_sonos_players: null
      - includeZones:
          - iot
        default: drop
        defaultLog: true
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
          - accept_app_control_from_sonos_players: null
      - ignoreZones:
          - local
          - iot
        default: drop
        rules:
          - accept_established: null
          - accept_related: null
          - drop_invalid: null
