---
# ----------------------
# Ansible configuration
# ----------------------

ansible_python_interpreter: /usr/bin/python3

# ---------------------
# System configuration
# ---------------------

vyos_save_config: true

vyos_hostname: fw
vyos_upstream_dns:
  - 1.1.1.1

vyos_remote_syslog:
  enabled: true
  endpoint: "{{ vyos_address_book_enriched['services']['k8s_promtail']['ipv4_addr'] }}"
  port: 1514

vyos_task_scheduler:
  tasks:
    update_cloudflare-ipv4:
      crontab: "0 */12 * * *"
      path: /config/scripts/cloudflare-ipv4.sh

# ---------------------
# Remote files to be managed
# ---------------------

vyos_managed_files:
  - url: https://www.cloudflare.com/ips-v4
    dest: /config/groups/cloudflare-ipv4
  - template: cloudflare-ipv4.sh.j2
    dest: /config/scripts/cloudflare-ipv4.sh
    mode: "0755"

# -------------------------
# Interfaces configuration
# -------------------------

vyos_interfaces:
  wan:
    interface: bond0
    vlan_id: 4000
    ipv4_addr: dhcp
  mgmt:
    interface: bond0
    ipv4_addr: true
    skip_creation: true
  wired:
    vlan_id: 10
    interface: bond0
    ipv4_addr: true
  servers:
    vlan_id: 20
    interface: bond0
    ipv4_addr: true
  # vlan_trusted:
  #   vlan_id: 20
  #   interface: eth1
  #   ipv4_addr: true
  wireless:
    vlan_id: 30
    interface: bond0
    ipv4_addr: true
  guest:
    vlan_id: 35
    interface: bond0
    ipv4_addr: true
  iot:
    vlan_id: 40
    interface: bond0
    ipv4_addr: true
  video:
    vlan_id: 50
    interface: bond0
    ipv4_addr: true
  rescue:
    interface: bond0
    vlan_id: 5
    ipv4_addr: true
  wg_trusted:
    interface: wg01
    ipv4_addr: true
    skip_creation: true

vyos_wireguard:
  servers:
    wg_trusted:
      private-key: "{{ secure_values['wireguard']['wg_trusted']['private_key'] }}"
      port: 51820
      peers:
        - name: iphone-ryan
          public-key: "{{ secure_values['wireguard']['wg_trusted']['iphone_ryan_public'] }}"
          ipv4_hostid: 2

# ------------------
# NAT configuration
# ------------------

vyos_nat:
  rules:
    - type: snat
      interface: wan
      source:
        address: 0.0.0.0/0
      destination:
        address: masquerade
    - type: dnat
      interface: wan
      protocol: tcp
      source:
        port: 443
      destination:
        address: "{{ vyos_address_book_enriched['services']['k8s_ingress']['ipv4_addr'] }}"
        port: 443
    - type: dnat
      interface: wan
      protocol: tcp
      source:
        port: 80
      destination:
        address: "{{ vyos_address_book_enriched['services']['k8s_ingress']['ipv4_addr'] }}"
        port: 80
    - type: dnat
      interface: iot
      protocol: tcp_udp
      source:
        address: "!{{ vyos_interfaces_enriched['iot']['ipv4_addr'] | ansible.netcommon.ipv4('address') }}"
        port: 53
      destination:
        address: "{{ vyos_interfaces_enriched['iot']['ipv4_addr'] | ansible.netcommon.ipv4('address') }}"
    - type: dnat
      interface: video
      protocol: tcp_udp
      source:
        address: "!{{ vyos_interfaces_enriched['video']['ipv4_addr'] | ansible.netcommon.ipv4('address') }}"
        port: 53
      destination:
        address: "{{ vyos_interfaces_enriched['video']['ipv4_addr'] | ansible.netcommon.ipv4('address') }}"
    - type: dnat
      interface: wired
      protocol: tcp_udp
      source:
        address: "!{{ vyos_interfaces_enriched['wired']['ipv4_addr'] | ansible.netcommon.ipv4('address') }}"
        port: 53
      destination:
        address: "{{ vyos_interfaces_enriched['wired']['ipv4_addr'] | ansible.netcommon.ipv4('address') }}"
    - type: dnat
      interface: wireless
      protocol: tcp_udp
      source:
        address: "!{{ vyos_interfaces_enriched['wireless']['ipv4_addr'] | ansible.netcommon.ipv4('address') }}"
        port: 53
      destination:
        address: "{{ vyos_interfaces_enriched['wireless']['ipv4_addr'] | ansible.netcommon.ipv4('address') }}"
    - type: dnat
      interface: wan
      protocol: tcp
      source:
        port: 32400
      destination:
        address: "{{ vyos_address_book_enriched['services']['k8s_plex']['ipv4_addr'] }}"
    - type: dnat
      interface: video
      protocol: udp
      source:
        address: "!{{ vyos_interfaces_enriched['video']['ipv4_addr'] | ansible.netcommon.ipv4('address') }}"
        port: 123
      destination:
        address: "{{ vyos_interfaces_enriched['video']['ipv4_addr'] | ansible.netcommon.ipv4('address') }}"
    - type: dnat
      interface: iot
      protocol: udp
      source:
        address: "!{{ vyos_interfaces_enriched['iot']['ipv4_addr'] | ansible.netcommon.ipv4('address') }}"
        port: 123
      destination:
        address: "{{ vyos_interfaces_enriched['iot']['ipv4_addr'] | ansible.netcommon.ipv4('address') }}"
    - type: dnat
      interface: servers
      protocol: udp
      source:
        address: "!{{ vyos_interfaces_enriched['servers']['ipv4_addr'] | ansible.netcommon.ipv4('address') }}"
        port: 123
      destination:
        address: "{{ vyos_interfaces_enriched['servers']['ipv4_addr'] | ansible.netcommon.ipv4('address') }}"

# -----------------------
# Firewall configuration
# Note: rules and zones are configured in their own respective host_vars files.
# -----------------------

vyos_firewall_network_groups:
  - name: cloudflare-ipv4
    from_file: /config/groups/cloudflare-ipv4

vyos_firewall_port_groups:
  - name: wireguard
    ports:
      - "{{ vyos_wireguard['servers']['wg_trusted']['port'] }}"

# ----------------------
# Routing configuration
# ----------------------

vyos_bgp:
  enabled: true
  local_as: 64512
  router_id: "{{ vyos_interfaces_enriched['servers']['ipv4_addr'] | ansible.netcommon.ipv4('address') }}"
  neighbor_groups:
    - group: k8s_nodes
      remote_as: 64512

# -----------------------
# Services configuration
# -----------------------

vyos_coredns:
  enabled: true
  interfaces:
    - mgmt
    - wired
    - servers
    - iot
    - wireless
    - video
    - rescue
    - wg_trusted
  config_path: /config/coredns
  container:
    repository: ghcr.io/k8s-at-home/coredns
    tag: v1.8.4
  k8s_gateway:
    enabled: true
    api_ip: "{{ vyos_address_book_enriched['services']['k8s_api']['ipv4_addr'] }}"
    domains: "{{ secure_values['coredns']['k8s_gateway']['domains'] }}"
    service_account_ns: kube-system
    service_account: excoredns

vyos_dhcp_server:
  enabled: true
  host-decl-name: true
  hostfile-update: true
  interfaces:
    mgmt: true
    wired:
      domain: "{{ vyos_domain }}"
    servers:
      domain: "{{ vyos_domain }}"
    iot:
      domain: "{{ vyos_domain }}"
    video:
      dns_server: "{{ vyos_address_book['services']['k8s_dns']['ipv4_addr'] }}"
    wireless:
      domain: "{{ vyos_domain }}"
    rescue:
      domain: "{{ vyos_domain }}"

# -----------------------
# Container configuration
# -----------------------

vyos_containers:
  udp-broadcast-relay-sonos:
    image:
      repository: ghcr.io/k8s-at-home/udp-broadcast-relay-redux
      tag: v1.25.0
    host-networking: true
    cap_add:
      - CAP_NET_RAW
    env:
      CFG_ID: "1"
      CFG_PORT: "1900"
      CFG_DEV: |-
        {{-
          [
            vyos_interfaces_enriched['wireless']['interface_complete'],
            vyos_interfaces_enriched['wired']['interface_complete'],
            vyos_interfaces_enriched['iot']['interface_complete']
          ] | join(",")
        -}}
      CFG_MULTICAST: "239.255.255.250"
  udp-broadcast-relay-hdhr:
    image:
      repository: ghcr.io/k8s-at-home/udp-broadcast-relay-redux
      tag: v1.25.0
    host-networking: true
    cap_add:
      - CAP_NET_RAW
    env:
      CFG_ID: "1"
      CFG_PORT: "65001"
      CFG_DEV: |-
        {{-
          [
            vyos_interfaces_enriched['wireless']['interface_complete'],
            vyos_interfaces_enriched['wired']['interface_complete'],
            vyos_interfaces_enriched['iot']['interface_complete']
          ] | join(",")
        -}}
      CFG_MULTICAST: "239.255.255.250"
  udp-broadcast-relay-mdns:
    image:
      repository: ghcr.io/k8s-at-home/udp-broadcast-relay-redux
      tag: v1.25.0
    host-networking: true
    cap_add:
      - CAP_NET_RAW
    env:
      CFG_ID: "2"
      CFG_PORT: "5353"
      CFG_DEV: |-
        {{-
          [
            vyos_interfaces_enriched['wireless']['interface_complete'],
            vyos_interfaces_enriched['wired']['interface_complete'],
            vyos_interfaces_enriched['iot']['interface_complete'],
            vyos_interfaces_enriched['servers']['interface_complete']
          ] | join(",")
        -}}
      CFG_MULTICAST: "224.0.0.251"
