---
# ----------------------
# Ansible configuration
# ----------------------

ansible_python_interpreter: /usr/bin/python3

# ---------------------
# System configuration
# ---------------------

vyos_save_config: true

vyos_hostname: fw
vyos_upstream_dns:
  - 1.1.1.1

vyos_timezone: "{{ timezone }}"

vyos_remote_syslog:
  enabled: false

vyos_task_scheduler:
  tasks:
    update_cloudflare-ipv4:
      crontab: "0 */12 * * *"
      path: /config/scripts/cloudflare-ipv4.sh

# ---------------------
# Remote files to be managed
# ---------------------

vyos_managed_files:
  - url: https://www.cloudflare.com/ips-v4
    dest: /config/groups/cloudflare-ipv4
  - template: cloudflare-ipv4.sh.j2
    dest: /config/scripts/cloudflare-ipv4.sh
    mode: "0755"
  - template: ipxe-metal.conf.j2
    dest: /config/dhcp/ipxe-metal.conf
    mode: "0755"
  - template: ha_proxy.cfg.j2
    dest: /config/haproxy/ha_proxy.cfg
    mode: "0755"
  - template: vector.yaml.j2
    dest: /config/vector-agent/vector.yaml
    mode: "0755"

# -------------------------
# Interfaces configuration
# -------------------------

vyos_interfaces:
  wan:
    interface: bond0
    vlan_id: 4000
    ipv4_addr: dhcp
  mgmt:
    interface: bond0
    ipv4_addr: true
    skip_creation: true
  wired:
    vlan_id: 10
    interface: bond0
    ipv4_addr: true
  servers:
    vlan_id: 20
    interface: bond0
    ipv4_addr: true
  # vlan_trusted:
  #   vlan_id: 20
  #   interface: eth1
  #   ipv4_addr: true
  wireless:
    vlan_id: 30
    interface: bond0
    ipv4_addr: true
  guest:
    vlan_id: 35
    interface: bond0
    ipv4_addr: true
  iot:
    vlan_id: 40
    interface: bond0
    ipv4_addr: true
  video:
    vlan_id: 50
    interface: bond0
    ipv4_addr: true
  rescue:
    interface: bond0
    vlan_id: 5
    ipv4_addr: true
  wg_trusted:
    interface: wg01
    ipv4_addr: true
    skip_creation: true
  services:
    interface: cni-services
    ipv4_addr: true
    skip_creation: true
  vti1:
    interface: vti1
    ipv4_addr: true
    skip_creation: true
  vti2:
    interface: vti2
    ipv4_addr: true
    skip_creation: true

vyos_wireguard:
  servers:
    wg_trusted:
      private-key: "{{ secure_values['wireguard']['wg_trusted']['private_key'] }}"
      port: 51820
      peers:
        - name: iphone-ryan
          public-key: "{{ secure_values['wireguard']['wg_trusted']['iphone_ryan_public'] }}"
          ipv4_hostid: 2

# -----------------------
# Firewall configuration
# Note: rules and zones are configured in their own respective host_vars files.
# -----------------------

vyos_firewall_network_groups:
  - name: cloudflare-ipv4
    from_file: /config/groups/cloudflare-ipv4

vyos_firewall_port_groups:
  - name: wireguard
    ports:
      - "{{ vyos_wireguard['servers']['wg_trusted']['port'] }}"

# ----------------------
# Routing configuration
# ----------------------

vyos_bgp:
  enabled: true
  local_as: 64512
  router_id: "{{ vyos_interfaces_enriched['servers']['ipv4_addr'] | ansible.netcommon.ipv4('address') }}"
  neighbor_groups:
    - group: k8s_nodes
      remote_as: 64512
    - group: azure_bgp
      remote_as: 65515

# -----------------------
# Services configuration
# -----------------------

vyos_coredns:
  enabled: true
  config_path: /config/coredns
  container:
    repository: ghcr.io/k8s-at-home/coredns
    tag: v1.8.4
    networks:
      services:
        ipv4_hostid: 3
  k8s_gateway:
    enabled: true
    api_ip: "{{ vyos_address_book_enriched['services']['k8s_api']['ipv4_addr'] }}"
    domains: "{{ secure_values['coredns']['k8s_gateway']['domains'] }}"
    service_account_ns: kube-system
    service_account: excoredns

vyos_dhcp_server:
  enabled: true
  host-decl-name: true
  hostfile-update: true
  interfaces:
    mgmt:
      domain: "{{ vyos_domain }}"
      # subnet_parameters: "option omada-address 10.45.10.20;;"
      dns_server: "{{ vyos_address_book_enriched['services']['vyos_coredns']['ipv4_addr'] }}"
    wired:
      domain: "{{ vyos_domain }}"
      dns_server: "{{ vyos_address_book_enriched['services']['vyos_coredns']['ipv4_addr'] }}"
    servers:
      subnet_parameters: "include &quot;/config/dhcp/ipxe-metal.conf&quot;;"
      dns_server: "{{ vyos_address_book_enriched['services']['vyos_coredns']['ipv4_addr'] }}"
    iot:
      domain: "{{ vyos_domain }}"
      dns_server: "{{ vyos_address_book_enriched['services']['vyos_coredns']['ipv4_addr'] }}"
    video:
      dns_server: "{{ vyos_address_book_enriched['services']['vyos_coredns']['ipv4_addr'] }}"
    wireless:
      domain: "{{ vyos_domain }}"
      dns_server: "{{ vyos_address_book_enriched['services']['vyos_coredns']['ipv4_addr'] }}"
    rescue:
      domain: "{{ vyos_domain }}"
      dns_server: "{{ vyos_address_book_enriched['services']['vyos_coredns']['ipv4_addr'] }}"
