# ------------------
# NAT configuration
# ------------------

vyos_nat:
  rules:
    - type: snat
      interface: wan
      source:
        address: 0.0.0.0/0
      destination:
        address: masquerade

    # ------------------
    # Port forwards
    # ------------------

    - type: dnat
      interface: wan
      protocol: tcp
      source:
        port: 443
      destination:
        address: "{{ vyos_address_book_enriched['services']['k8s_ingress']['ipv4_addr'] }}"
        port: 443
    - type: dnat
      interface: wan
      protocol: tcp
      source:
        port: 80
      destination:
        address: "{{ vyos_address_book_enriched['services']['k8s_ingress']['ipv4_addr'] }}"
        port: 80
    - type: dnat
      interface: wan
      protocol: tcp
      source:
        port: 32400
      destination:
        address: "{{ vyos_address_book_enriched['services']['k8s_plex']['ipv4_addr'] }}"
    - type: dnat
      interface: wan
      protocol: tcp
      source:
        port: 4994
      destination:
        address: "{{ vyos_address_book_enriched['hosts']['flex']['ipv4_addr'] }}"
    - type: dnat
      interface: wan
      protocol: udp
      source:
        port: 4993
      destination:
        address: "{{ vyos_address_book_enriched['hosts']['flex']['ipv4_addr'] }}"

    # ------------------
    # Force DNS to gateway
    # ------------------

    - type: dnat
      interface: iot
      protocol: tcp_udp
      source:
        # address: "!{{ vyos_address_book_enriched['services']['k8s_dns']['ipv4_addr'] }}"
        address: "!{{ vyos_address_book_enriched['services']['vyos_coredns']['ipv4_addr'] }}"
        # address: "!1.1.1.1"
        port: 53
      destination:
        # address: "{{ vyos_address_book_enriched['services']['k8s_dns']['ipv4_addr'] }}"
        address: "{{ vyos_address_book_enriched['services']['vyos_coredns']['ipv4_addr'] }}"
        # address: "1.1.1.1"
    - type: dnat
      interface: video
      protocol: tcp_udp
      source:
        address: "!{{ vyos_address_book_enriched['services']['k8s_dns']['ipv4_addr'] }}"
        # address: "!{{ vyos_address_book_enriched['services']['vyos_coredns']['ipv4_addr'] }}"
        # address: "!1.1.1.1"
        port: 53
      destination:
        address: "{{ vyos_address_book_enriched['services']['k8s_dns']['ipv4_addr'] }}"
        # address: "{{ vyos_address_book_enriched['services']['vyos_coredns']['ipv4_addr'] }}"
        # address: "1.1.1.1"
    - type: dnat
      interface: wired
      protocol: tcp_udp
      source:
        # address: "!{{ vyos_address_book_enriched['services']['k8s_dns']['ipv4_addr'] }}"
        address: "!{{ vyos_address_book_enriched['services']['vyos_coredns']['ipv4_addr'] }}"
        # address: "!1.1.1.1"
        port: 53
      destination:
        # address: "{{ vyos_address_book_enriched['services']['k8s_dns']['ipv4_addr'] }}"
        address: "{{ vyos_address_book_enriched['services']['vyos_coredns']['ipv4_addr'] }}"
        # address: "1.1.1.1"
    - type: dnat
      interface: wireless
      protocol: tcp_udp
      source:
        # address: "!{{ vyos_address_book_enriched['services']['k8s_dns']['ipv4_addr'] }}"
        address: "!{{ vyos_address_book_enriched['services']['vyos_coredns']['ipv4_addr'] }}"
        # address: "!1.1.1.1"
        port: 53
      destination:
        # address: "{{ vyos_address_book_enriched['services']['k8s_dns']['ipv4_addr'] }}"
        address: "{{ vyos_address_book_enriched['services']['vyos_coredns']['ipv4_addr'] }}"
        # address: "1.1.1.1"
    - type: dnat
      interface: servers
      protocol: tcp_udp
      source:
        address: "!{{ vyos_address_book_enriched['services']['vyos_coredns']['ipv4_addr'] }}"
        port: 53
      destination:
        address: "{{ vyos_address_book_enriched['services']['vyos_coredns']['ipv4_addr'] }}"


    # ------------------
    # Force NTP to gateway
    # ------------------

    - type: dnat
      interface: video
      protocol: udp
      source:
        address: "!{{ vyos_interfaces_enriched['video']['ipv4_addr'] | ansible.netcommon.ipv4('address') }}"
        port: 123
      destination:
        address: "{{ vyos_interfaces_enriched['video']['ipv4_addr'] | ansible.netcommon.ipv4('address') }}"
    - type: dnat
      interface: iot
      protocol: udp
      source:
        address: "!{{ vyos_interfaces_enriched['iot']['ipv4_addr'] | ansible.netcommon.ipv4('address') }}"
        port: 123
      destination:
        address: "{{ vyos_interfaces_enriched['iot']['ipv4_addr'] | ansible.netcommon.ipv4('address') }}"
    - type: dnat
      interface: servers
      protocol: udp
      source:
        address: "!{{ vyos_interfaces_enriched['servers']['ipv4_addr'] | ansible.netcommon.ipv4('address') }}"
        port: 123
      destination:
        address: "{{ vyos_interfaces_enriched['servers']['ipv4_addr'] | ansible.netcommon.ipv4('address') }}"
