---

- name: Deploy kube-router
  command: "kubectl apply -f {{ REPO_ROOT}}/ansible/manifests/generic-kuberouter-only-advertise-routes.yaml"
  become: no
  environment:
    KUBECONFIG: "{{ REPO_ROOT }}/kubeconfig"

- name: Deploy Cilium
  shell: |
    helm upgrade -i cilium cilium/cilium --version {{ cni.cilium.helmVersion }} \
    --set global.registry="docker.io/cilium" \
    --set global.tag="{{ cni.cilium.imageVersion }}" \
    --set global.tunnel="disabled" \
    --set global.nativeRoutingCIDR="{{ cni.podCIDR }}" \
    --set global.externalIPs.enabled="true" \
    --set global.ipam.operator.clusterPoolIPv4PodCIDR="{{ cni.podCIDR }}" \
    --set global.ipam.operator.clusterPoolIPv4MaskSize="{{ cni.podMaskSize }}" \
    --set global.containerRuntime.integration="containerd" \
    --set global.containerRuntime.socketPath="/var/run/k3s/containerd/containerd.sock" \
    --set global.kubeProxyReplacement="strict" \
    --namespace kube-system
  environment:
    KUBECONFIG: "{{ REPO_ROOT }}/kubeconfig"
